package gents

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func referencedTypeNames(file *onkir.File) []string {
	seen := map[string]bool{}
	var names []string
	add := func(name string) {
		if !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add(m.Request.Name)
			add(m.Response.Name)
			for _, errType := range m.ErrorTypes {
				add(errType.Name)
			}
		}
	}
	return names
}

func clientEncodeHelperNames(file *onkir.File) []string {
	seen := map[string]bool{}
	var names []string
	for _, s := range file.Services {
		for _, m := range s.Methods {
			if messageNeedsEncodeHelper(m.Request) && !seen[m.Request.Name] {
				seen[m.Request.Name] = true
				names = append(names, m.Request.Name)
			}
		}
	}
	return names
}

func GenerateClient(file *onkir.File) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := &Printer{}
	p.P("// Code generated by onek. DO NOT EDIT.")
	if names := referencedTypeNames(file); len(names) > 0 {
		p.P(`import type { `, strings.Join(names, ", "), ` } from "./types";`)
	}
	if helpers := clientEncodeHelperNames(file); len(helpers) > 0 {
		var fns []string
		for _, h := range helpers {
			fns = append(fns, "encode"+h)
		}
		p.P(`import { `, strings.Join(fns, ", "), ` } from "./types";`)
	}
	p.P()

	for _, s := range file.Services {
		writeClientClass(p, s)
	}

	return p.Bytes()
}

func writeClientClass(p *Printer, s *onkir.Service) {
	p.P("export interface ", s.Name, "ClientOptions {")
	p.P("headers?: Record<string, string>;")
	p.P("}")
	p.P()

	p.P("export class ", s.Name, "Client {")
	p.P("private baseUrl: string;")
	p.P("private options: ", s.Name, "ClientOptions;")
	p.P()
	p.P("constructor(baseUrl: string, options: ", s.Name, "ClientOptions = {}) {")
	p.P("this.baseUrl = baseUrl;")
	p.P("this.options = options;")
	p.P("}")
	p.P()

	for _, m := range s.Methods {
		if m.IsStream() {
			writeSSEClientMethod(p, s, m)
		} else {
			writeClientMethod(p, s, m)
		}
	}

	p.P("}")
	p.P()
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := isBodyBearingVerb(verb)

	p.P("async ", CamelCase(m.Name), "(req: ", m.Request.Name, "): Promise<", m.Response.Name, "> {")
	p.P(fmt.Sprintf("let path = %q;", fullPath))
	for _, paramName := range pathParamNames(path) {
		field := findField(m.Request, paramName)
		if field == nil {
			continue
		}
		p.P(fmt.Sprintf(
			"path = path.replace(%q, encodeURIComponent(String(req.%s)));",
			"{"+paramName+"}", field.Name,
		))
	}

	if !bodyBearing {
		writeClientQueryParams(p, m.Request)
	}

	p.P("const res = await fetch(this.baseUrl + path, {")
	p.P(fmt.Sprintf("method: %q,", strings.ToUpper(verb)))
	if bodyBearing {
		p.P(`headers: { "Content-Type": "application/json", ...this.options.headers },`)
		if messageNeedsEncodeHelper(m.Request) {
			p.P("body: JSON.stringify(encode", m.Request.Name, "(req)),")
		} else {
			p.P("body: JSON.stringify(req),")
		}
	} else {
		p.P("headers: { ...this.options.headers },")
	}
	p.P("});")
	p.P()

	p.P("if (!res.ok) {")
	writeClientErrorHandling(p, m)
	p.P("}")
	p.P()
	p.P("return (await res.json()) as ", m.Response.Name, ";")
	p.P("}")
	p.P()
}

func findField(msg *onkir.Message, name string) *onkir.Field {
	for _, f := range msg.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

func pathParamNames(path string) []string {
	var names []string
	start := -1
	for i, c := range path {
		if c == '{' {
			start = i + 1
		} else if c == '}' && start >= 0 {
			names = append(names, path[start:i])
			start = -1
		}
	}
	return names
}

func isBodyBearingVerb(verb string) bool {
	return verb == "post" || verb == "put" || verb == "patch" || verb == "query"
}

func writeClientQueryParams(p *Printer, req *onkir.Message) {
	p.P("const query = new URLSearchParams();")
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		p.P("if (req.", field.Name, " !== undefined) {")
		p.P(fmt.Sprintf("query.set(%q, String(req.%s));", queryName, field.Name))
		p.P("}")
	}
	p.P(`const queryStr = query.toString();`)
	p.P(`if (queryStr) { path += "?" + queryStr; }`)
}

func writeClientErrorHandling(p *Printer, m *onkir.Method) {
	p.P("const body = await res.text();")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if (res.status === %d) {", status))
		p.P("throw JSON.parse(body) as ", errType.Name, ";")
		p.P("}")
	}
	p.P(`throw new Error("unexpected status " + res.status + ": " + body);`)
}
