// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: proto/services/portfolio_service.proto

package services

import (
	models "github.com/1homsi/onekit/examples/enum-params/api/proto/models"
)

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// PortfolioServiceServer is the server API for PortfolioService service.
type PortfolioServiceServer interface {
	GetPortfolio(context.Context, *GetPortfolioRequest) (*models.PortfolioSummary, error)
	GetByAssetClass(context.Context, *GetByAssetClassRequest) (*models.PortfolioSummary, error)
	SearchByAssetClasses(context.Context, *SearchByAssetClassesRequest) (*models.PortfolioSummary, error)
}

// RegisterPortfolioServiceServer registers the HTTP handlers for service PortfolioService to the given mux.
func RegisterPortfolioServiceServer(server PortfolioServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getPortfolioServiceHeaders()

	methodHeaders := getGetPortfolioHeaders()
	getPortfolioHandler := BindingMiddleware[GetPortfolioRequest](
		genericHandler(server.GetPortfolio, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getPortfolioPathParams, getPortfolioQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	getPortfolioHandler = config.wrapHandler(getPortfolioHandler, RequestMetadata{
		Service:     "examples.enumparams.services.PortfolioService",
		Method:      "GetPortfolio",
		Procedure:   "examples.enumparams.services.PortfolioService.GetPortfolio",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/portfolio",
	})
	config.mux.Handle("GET /api/v1/portfolio", getPortfolioHandler)

	methodHeaders = getGetByAssetClassHeaders()
	getByAssetClassHandler := BindingMiddleware[GetByAssetClassRequest](
		genericHandler(server.GetByAssetClass, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getByAssetClassPathParams, getByAssetClassQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	getByAssetClassHandler = config.wrapHandler(getByAssetClassHandler, RequestMetadata{
		Service:     "examples.enumparams.services.PortfolioService",
		Method:      "GetByAssetClass",
		Procedure:   "examples.enumparams.services.PortfolioService.GetByAssetClass",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/portfolio/asset-class/{asset_class}",
	})
	config.mux.Handle("GET /api/v1/portfolio/asset-class/{asset_class}", getByAssetClassHandler)

	methodHeaders = getSearchByAssetClassesHeaders()
	searchByAssetClassesHandler := BindingMiddleware[SearchByAssetClassesRequest](
		genericHandler(server.SearchByAssetClasses, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		searchByAssetClassesPathParams, searchByAssetClassesQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	searchByAssetClassesHandler = config.wrapHandler(searchByAssetClassesHandler, RequestMetadata{
		Service:     "examples.enumparams.services.PortfolioService",
		Method:      "SearchByAssetClasses",
		Procedure:   "examples.enumparams.services.PortfolioService.SearchByAssetClasses",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/portfolio/search",
	})
	config.mux.Handle("GET /api/v1/portfolio/search", searchByAssetClassesHandler)

	return nil
}

// getPortfolioServiceHeaders returns the service-level required headers for PortfolioService
func getPortfolioServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetPortfolioHeaders returns the method-level required headers for GetPortfolio
func getGetPortfolioHeaders() []*onekithttp.Header {
	return nil
}

// getGetByAssetClassHeaders returns the method-level required headers for GetByAssetClass
func getGetByAssetClassHeaders() []*onekithttp.Header {
	return nil
}

// getSearchByAssetClassesHeaders returns the method-level required headers for SearchByAssetClasses
func getSearchByAssetClassesHeaders() []*onekithttp.Header {
	return nil
}

// getPortfolioPathParams contains path parameter configuration for GetPortfolio
var getPortfolioPathParams = []PathParamConfig{}

// getPortfolioQueryParams contains query parameter configuration for GetPortfolio
var getPortfolioQueryParams = []QueryParamConfig{
	{QueryName: "timeframe", FieldName: "timeframe", Required: false},
}

// getByAssetClassPathParams contains path parameter configuration for GetByAssetClass
var getByAssetClassPathParams = []PathParamConfig{
	{URLParam: "asset_class", FieldName: "asset_class"},
}

// getByAssetClassQueryParams contains query parameter configuration for GetByAssetClass
var getByAssetClassQueryParams = []QueryParamConfig{
	{QueryName: "timeframe", FieldName: "timeframe", Required: false},
}

// searchByAssetClassesPathParams contains path parameter configuration for SearchByAssetClasses
var searchByAssetClassesPathParams = []PathParamConfig{}

// searchByAssetClassesQueryParams contains query parameter configuration for SearchByAssetClasses
var searchByAssetClassesQueryParams = []QueryParamConfig{
	{QueryName: "class", FieldName: "asset_classes", Required: false},
	{QueryName: "tag", FieldName: "tags", Required: false},
}
