package tsclientgen

import (
	"fmt"
	"net/http"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/1homsi/onekit/internal/annotations"
	"github.com/1homsi/onekit/internal/tscommon"
)

// Generator handles TypeScript HTTP client code generation for protobuf services.
type Generator struct {
	plugin *protogen.Plugin
}

// New creates a new TypeScript client generator.
func New(plugin *protogen.Plugin) *Generator {
	return &Generator{
		plugin: plugin,
	}
}

// Generate processes all files and generates TypeScript clients.
func (g *Generator) Generate() error {
	for _, file := range g.plugin.Files {
		if !file.Generate {
			continue
		}
		if err := g.generateFile(file); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateFile(file *protogen.File) error {
	if len(file.Services) == 0 {
		return nil
	}
	return g.generateClientFile(file)
}

func (g *Generator) generateClientFile(file *protogen.File) error {
	// Output .ts file alongside the proto source
	filename := file.GeneratedFilenamePrefix + "_client.ts"
	gf := g.plugin.NewGeneratedFile(filename, "")

	// Collect all referenced messages and enums
	ms := collectServiceMessages(file)

	// Helper to print to generated file
	p := func(format string, args ...interface{}) {
		if len(args) == 0 {
			gf.P(format)
		} else {
			gf.P(fmt.Sprintf(format, args...))
		}
	}

	// 1. Header
	g.writeHeader(p, file)

	// 2. Message interfaces
	for _, msg := range ms.OrderedMessages() {
		generateInterface(p, msg)
	}

	// 3. Enum types
	for _, enum := range ms.OrderedEnums() {
		generateEnumType(p, enum)
	}

	// 4. Error types
	g.writeErrorTypes(p)

	// 5. Retry options (shared by all services in this file)
	g.writeRetryOptions(p)

	// 5. Per service: options + client class
	for _, service := range file.Services {
		if err := g.generateServiceClient(p, service); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) writeHeader(p printer, file *protogen.File) {
	p("// Code generated by protoc-gen-onekit-ts-client. DO NOT EDIT.")
	p("// source: %s", file.Desc.Path())
	p("")
}

func (g *Generator) writeErrorTypes(p printer) {
	tscommon.WriteErrorTypes(tscommon.Printer(p))
}

// writeRetryOptions emits the shared RetryOptions interface once per file.
func (g *Generator) writeRetryOptions(p printer) {
	p("export interface RetryOptions {")
	p("  /** Total number of attempts including the first. Default 1 (no retries). */")
	p("  maxAttempts?: number;")
	p("  /** Delay before the first retry in milliseconds; doubles each retry. Default 250. */")
	p("  baseDelayMs?: number;")
	p("  /** Status codes that trigger a retry. Default [429, 502, 503, 504]. */")
	p("  retryableStatuses?: number[];")
	p("}")
	p("")
}

func (g *Generator) generateServiceClient(p printer, service *protogen.Service) error {
	serviceName := service.GoName

	// Client options interface
	g.generateClientOptionsInterface(p, service)

	// Call options interface
	g.generateCallOptionsInterface(p, service)

	// Client class
	if err := g.generateClientClass(p, service); err != nil {
		return err
	}

	_ = serviceName
	return nil
}

// generateClientOptionsInterface generates the {Service}ClientOptions interface.
func (g *Generator) generateClientOptionsInterface(p printer, service *protogen.Service) {
	serviceName := service.GoName

	p("export interface %sClientOptions {", serviceName)
	p("  fetch?: typeof fetch;")
	p("  defaultHeaders?: Record<string, string>;")
	p("  /** Retry policy for transient failures. Never applied to SSE streams. */")
	p("  retry?: RetryOptions;")

	// Add typed properties for service-level headers
	serviceHeaders := annotations.GetServiceHeaders(service)
	for _, header := range serviceHeaders {
		propName := headerNameToPropertyName(header.GetName())
		p("  %s?: string;", propName)
	}

	p("}")
	p("")
}

// generateCallOptionsInterface generates the {Service}CallOptions interface.
func (g *Generator) generateCallOptionsInterface(p printer, service *protogen.Service) {
	serviceName := service.GoName

	p("export interface %sCallOptions {", serviceName)
	p("  headers?: Record<string, string>;")
	p("  signal?: AbortSignal;")
	p("  /** Per-call retry policy; overrides the client-level policy. */")
	p("  retry?: RetryOptions;")

	// Add typed properties for service-level headers (also available per-call)
	serviceHeaders := annotations.GetServiceHeaders(service)
	for _, header := range serviceHeaders {
		propName := headerNameToPropertyName(header.GetName())
		p("  %s?: string;", propName)
	}

	// Add typed properties for method-level headers
	seen := make(map[string]bool)
	for _, method := range service.Methods {
		methodHeaders := annotations.GetMethodHeaders(method)
		for _, header := range methodHeaders {
			propName := headerNameToPropertyName(header.GetName())
			if seen[propName] {
				continue
			}
			seen[propName] = true
			p("  %s?: string;", propName)
		}
	}

	p("}")
	p("")
}

// generateClientClass generates the client class with constructor and methods.
func (g *Generator) generateClientClass(p printer, service *protogen.Service) error {
	serviceName := service.GoName

	p("export class %sClient {", serviceName)

	// Private fields
	p("  private baseURL: string;")
	p("  private fetchFn: typeof fetch;")
	p("  private defaultHeaders: Record<string, string>;")
	p("  private retry?: RetryOptions;")
	p("")

	// Constructor
	g.generateConstructor(p, service)

	// RPC methods
	for _, method := range service.Methods {
		if err := g.generateRPCMethod(p, service, method); err != nil {
			return err
		}
	}

	// Retry-aware fetch executor
	g.generateDoFetch(p)

	// Error handler
	g.generateHandleError(p)

	p("}")
	p("")
	return nil
}

// generateConstructor generates the client constructor.
func (g *Generator) generateConstructor(p printer, service *protogen.Service) {
	serviceName := service.GoName

	p("  constructor(baseURL: string, options?: %sClientOptions) {", serviceName)
	p(`    this.baseURL = baseURL.replace(/\/+$/, "");`)
	p("    this.fetchFn = options?.fetch ?? globalThis.fetch;")
	p("    this.defaultHeaders = { ...options?.defaultHeaders };")
	p("    this.retry = options?.retry;")

	// Apply service-level headers from options
	serviceHeaders := annotations.GetServiceHeaders(service)
	for _, header := range serviceHeaders {
		propName := headerNameToPropertyName(header.GetName())
		headerName := header.GetName()
		p("    if (options?.%s) {", propName)
		p(`      this.defaultHeaders["%s"] = options.%s;`, headerName, propName)
		p("    }")
	}

	p("  }")
	p("")
}

// rpcMethodConfig holds the configuration for generating an RPC method.
type rpcMethodConfig struct {
	serviceName       string
	methodName        string
	httpMethod        string
	fullPath          string
	pathParams        []string
	queryParams       []annotations.QueryParam
	hasBody           bool
	isSSE             bool
	bodyFieldJSONName string // non-empty when body: "<field>" selects a sub-message body
}

// Empty protobuf messages can still be meaningful request values, such as
// JSON bodies for POST/PUT/PATCH, so don't infer usage from field count alone.
func (cfg *rpcMethodConfig) requestParamName() string {
	usesQueryParams := (cfg.httpMethod == http.MethodGet || cfg.httpMethod == http.MethodDelete) &&
		len(cfg.queryParams) > 0
	if cfg.hasBody || len(cfg.pathParams) > 0 || usesQueryParams {
		return "req"
	}
	return "_req"
}

func (g *Generator) buildRPCMethodConfig(service *protogen.Service, method *protogen.Method) *rpcMethodConfig {
	serviceName := service.GoName
	methodName := method.GoName

	httpConfig := annotations.GetMethodHTTPConfig(method)
	httpMethod := http.MethodPost
	httpPath := "/" + annotations.LowerFirst(methodName)
	var pathParams []string

	if httpConfig != nil {
		if httpConfig.Method != "" {
			httpMethod = httpConfig.Method
		}
		if httpConfig.Path != "" {
			httpPath = httpConfig.Path
		}
		pathParams = httpConfig.PathParams
	}

	// Get base path from service config
	basePath := annotations.GetServiceBasePath(service)

	// Combine base path and method path
	fullPath := annotations.BuildHTTPPath(basePath, httpPath)

	isSSE := httpConfig != nil && httpConfig.Stream

	return &rpcMethodConfig{
		serviceName: serviceName,
		methodName:  methodName,
		httpMethod:  httpMethod,
		fullPath:    fullPath,
		pathParams:  pathParams,
		queryParams: annotations.GetQueryParams(method.Input),
		hasBody:     httpMethod == "POST" || httpMethod == "PUT" || httpMethod == "PATCH",
		isSSE:       isSSE,
	}
}

// generateRPCMethod generates a single async RPC method.
func (g *Generator) generateRPCMethod(p printer, service *protogen.Service, method *protogen.Method) error {
	cfg := g.buildRPCMethodConfig(service, method)

	bodyField, err := annotations.GetBodyField(method)
	if err != nil && !annotations.IsNoBodyField(err) {
		return err
	}
	if bodyField != nil {
		cfg.bodyFieldJSONName = bodyField.Desc.JSONName()
	}

	if cfg.isSSE {
		g.generateSSERPCMethod(p, service, method, cfg)
		return nil
	}

	inputType := string(method.Input.Desc.Name())
	outputType := g.resolveOutputType(method)

	tsMethodName := annotations.LowerFirst(cfg.methodName)

	reqParam := cfg.requestParamName()
	p("  async %s(%s: %s, options?: %sCallOptions): Promise<%s> {",
		tsMethodName, reqParam, inputType, cfg.serviceName, outputType)

	// Build URL with path params
	g.generateURLBuilding(p, cfg)

	// Build headers
	g.generateHeaderMerging(p, service, method)

	// Build fetch options
	g.generateFetchCall(p, cfg)

	// Handle response
	g.generateResponseHandling(p, method)

	p("  }")
	p("")
	return nil
}

// generateSSERPCMethod generates an async generator method for SSE streaming.
func (g *Generator) generateSSERPCMethod(
	p printer,
	service *protogen.Service,
	method *protogen.Method,
	cfg *rpcMethodConfig,
) {
	inputType := string(method.Input.Desc.Name())
	outputType := g.resolveOutputType(method)
	tsMethodName := annotations.LowerFirst(cfg.methodName)

	reqParam := cfg.requestParamName()
	p("  async *%s(%s: %s, options?: %sCallOptions): AsyncGenerator<%s> {",
		tsMethodName, reqParam, inputType, cfg.serviceName, outputType)

	// Build URL with path params
	g.generateURLBuilding(p, cfg)

	// Build headers (use Accept instead of Content-Type for SSE)
	g.generateSSEHeaderMerging(p, service, method)

	// Fetch call
	g.generateSSEFetchCall(p, cfg)

	// SSE stream parsing
	g.generateSSEStreamParsing(p, outputType)

	p("  }")
	p("")
}

// generateSSEHeaderMerging generates header construction for SSE requests.
func (g *Generator) generateSSEHeaderMerging(p printer, service *protogen.Service, method *protogen.Method) {
	p("    const headers: Record<string, string> = {")
	p(`      "Accept": "text/event-stream",`)
	p("      ...this.defaultHeaders,")
	p("      ...options?.headers,")
	p("    };")

	// Apply service-level headers from call options
	serviceHeaders := annotations.GetServiceHeaders(service)
	for _, header := range serviceHeaders {
		propName := headerNameToPropertyName(header.GetName())
		headerName := header.GetName()
		p("    if (options?.%s) headers[\"%s\"] = options.%s;", propName, headerName, propName)
	}

	// Apply method-level headers from call options
	methodHeaders := annotations.GetMethodHeaders(method)
	for _, header := range methodHeaders {
		propName := headerNameToPropertyName(header.GetName())
		headerName := header.GetName()
		p("    if (options?.%s) headers[\"%s\"] = options.%s;", propName, headerName, propName)
	}

	p("")
}

// generateSSEFetchCall generates the fetch invocation for SSE.
func (g *Generator) generateSSEFetchCall(p printer, cfg *rpcMethodConfig) {
	if cfg.hasBody {
		p("    const resp = await this.fetchFn(url, {")
		p(`      method: "%s",`, cfg.httpMethod)
		p("      headers,")
		p("      body: JSON.stringify(req),")
		p("      signal: options?.signal,")
		p("    });")
	} else {
		p("    const resp = await this.fetchFn(url, {")
		p(`      method: "%s",`, cfg.httpMethod)
		p("      headers,")
		p("      signal: options?.signal,")
		p("    });")
	}
	p("")

	p("    if (!resp.ok) {")
	p("      return this.handleError(resp);")
	p("    }")
	p("")
}

// generateSSEStreamParsing generates the ReadableStream SSE parsing logic.
func (g *Generator) generateSSEStreamParsing(p printer, outputType string) {
	p("    const reader = resp.body!.getReader();")
	p("    const decoder = new TextDecoder();")
	p(`    let buffer = "";`)
	p("")
	p("    try {")
	p("      while (true) {")
	p("        const { done, value } = await reader.read();")
	p("        if (done) break;")
	p("        buffer += decoder.decode(value, { stream: true });")
	p(`        const lines = buffer.split("\n");`)
	p(`        buffer = lines.pop() || "";`)
	p("        for (const line of lines) {")
	p(`          if (line.startsWith("data: ")) {`)
	p("            const data = line.slice(6);")
	p("            yield JSON.parse(data) as %s;", outputType)
	p("          }")
	p("        }")
	p("      }")
	p("    } finally {")
	p("      reader.releaseLock();")
	p("    }")
}

// resolveOutputType returns the TypeScript return type, handling root unwrap.
func (g *Generator) resolveOutputType(method *protogen.Method) string {
	msg := method.Output
	if annotations.IsRootUnwrap(msg) {
		return rootUnwrapTSType(msg)
	}
	return string(msg.Desc.Name())
}

// generateURLBuilding generates URL construction with path and query params.
func (g *Generator) generateURLBuilding(p printer, cfg *rpcMethodConfig) {
	p(`    let path = "%s";`, cfg.fullPath)

	// Path parameter substitution
	for _, param := range cfg.pathParams {
		jsonName := snakeToLowerCamel(param)
		p(`    path = path.replace("{%s}", encodeURIComponent(String(req.%s)));`, param, jsonName)
	}

	// Query parameters. With body field selection, non-body fields bind from
	// path/query even on POST/PUT/PATCH, so query encoding applies there too.
	useQuery := cfg.httpMethod == "GET" || cfg.httpMethod == "DELETE" || cfg.bodyFieldJSONName != ""
	//nolint:nestif // Query param generation requires multiple nested conditions
	if useQuery && len(cfg.queryParams) > 0 {
		p("    const params = new URLSearchParams();")
		for _, qp := range cfg.queryParams {
			// Handle repeated fields: use forEach + append for multi-value params
			if qp.Field != nil && qp.Field.Desc.IsList() {
				p("    if (req.%s && req.%s.length > 0) req.%s.forEach(v => params.append(\"%s\", String(v)));",
					qp.FieldJSONName, qp.FieldJSONName, qp.FieldJSONName, qp.ParamName)
				continue
			}

			// Use field-aware zero check when field reference is available
			var check string
			if qp.Field != nil {
				check = tsZeroCheckForField(qp.Field)
			} else {
				check = tsZeroCheck(qp.FieldKind)
			}
			if check == "" {
				// bool: only add if true (undefined is already falsy)
				p("    if (req.%s) params.set(\"%s\", String(req.%s));",
					qp.FieldJSONName, qp.ParamName, qp.FieldJSONName)
			} else {
				// Guard against undefined/null before zero-value check
				p("    if (req.%s != null && req.%s%s) params.set(\"%s\", String(req.%s));",
					qp.FieldJSONName, qp.FieldJSONName, check, qp.ParamName, qp.FieldJSONName)
			}
		}
		p(`    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");`)
	} else {
		p("    const url = this.baseURL + path;")
	}

	p("")
}

// generateHeaderMerging generates header construction from defaults + options.
func (g *Generator) generateHeaderMerging(p printer, service *protogen.Service, method *protogen.Method) {
	p("    const headers: Record<string, string> = {")
	p(`      "Content-Type": "application/json",`)
	p("      ...this.defaultHeaders,")
	p("      ...options?.headers,")
	p("    };")

	// Apply service-level headers from call options
	serviceHeaders := annotations.GetServiceHeaders(service)
	for _, header := range serviceHeaders {
		propName := headerNameToPropertyName(header.GetName())
		headerName := header.GetName()
		p("    if (options?.%s) headers[\"%s\"] = options.%s;", propName, headerName, propName)
	}

	// Apply method-level headers from call options
	methodHeaders := annotations.GetMethodHeaders(method)
	for _, header := range methodHeaders {
		propName := headerNameToPropertyName(header.GetName())
		headerName := header.GetName()
		p("    if (options?.%s) headers[\"%s\"] = options.%s;", propName, headerName, propName)
	}

	p("")
}

// generateFetchCall generates the fetch invocation (retry-aware).
func (g *Generator) generateFetchCall(p printer, cfg *rpcMethodConfig) {
	if cfg.hasBody {
		bodyExpr := "req"
		if cfg.bodyFieldJSONName != "" {
			bodyExpr = fmt.Sprintf("req.%s ?? {}", cfg.bodyFieldJSONName)
		}
		p("    const resp = await this.doFetch(url, {")
		p(`      method: "%s",`, cfg.httpMethod)
		p("      headers,")
		p("      body: JSON.stringify(%s),", bodyExpr)
		p("      signal: options?.signal,")
		p("    }, options?.retry ?? this.retry);")
	} else {
		p("    const resp = await this.doFetch(url, {")
		p(`      method: "%s",`, cfg.httpMethod)
		p("      headers,")
		p("      signal: options?.signal,")
		p("    }, options?.retry ?? this.retry);")
	}
	p("")
}

// generateResponseHandling generates response parsing and error handling.
func (g *Generator) generateResponseHandling(p printer, method *protogen.Method) {
	outputType := g.resolveOutputType(method)

	p("    if (!resp.ok) {")
	p("      return this.handleError(resp);")
	p("    }")
	p("")
	p("    return await resp.json() as %s;", outputType)
}

// generateDoFetch generates the private retry-aware fetch executor.
func (g *Generator) generateDoFetch(p printer) {
	p("  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {")
	p("    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);")
	p("    const baseDelayMs = retry?.baseDelayMs ?? 250;")
	p("    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];")
	p("    let lastError: unknown;")
	p("    for (let attempt = 0; attempt < maxAttempts; attempt++) {")
	p("      if (attempt > 0) {")
	p("        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));")
	p("      }")
	p("      try {")
	p("        const resp = await this.fetchFn(url, init);")
	p("        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {")
	p("          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, \"\");")
	p("          continue;")
	p("        }")
	p("        return resp;")
	p("      } catch (e) {")
	p("        // Aborts are intentional; never retry them.")
	p(`        if (e instanceof Error && e.name === "AbortError") throw e;`)
	p("        lastError = e;")
	p("      }")
	p("    }")
	p("    throw lastError;")
	p("  }")
	p("")
}

// generateHandleError generates the private error handler method.
func (g *Generator) generateHandleError(p printer) {
	p("  private async handleError(resp: Response): Promise<never> {")
	p("    const body = await resp.text();")
	p("    if (resp.status === 400) {")
	p("      try {")
	p("        const parsed = JSON.parse(body);")
	p("        if (parsed.violations) {")
	p("          throw new ValidationError(parsed.violations);")
	p("        }")
	p("      } catch (e) {")
	p("        if (e instanceof ValidationError) throw e;")
	p("      }")
	p("    }")
	p("    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);")
	p("  }")
}
