// Code generated by protoc-gen-onekit-ts-client. DO NOT EDIT.
// source: body_selection.proto

export interface UpdateProfileRequest {
  userId: string;
  notify: boolean;
  profile?: Profile;
}

export interface Profile {
  displayName: string;
  bio: string;
}

export interface CreateNoteRequest {
  collection: string;
  note?: Note;
}

export interface Note {
  id: string;
  title: string;
  content: string;
}

export interface CreateProfileRequest {
  profile?: Profile;
}

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface RetryOptions {
  /** Total number of attempts including the first. Default 1 (no retries). */
  maxAttempts?: number;
  /** Delay before the first retry in milliseconds; doubles each retry. Default 250. */
  baseDelayMs?: number;
  /** Status codes that trigger a retry. Default [429, 502, 503, 504]. */
  retryableStatuses?: number[];
}

export interface BodySelectServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  /** Retry policy for transient failures. Never applied to SSE streams. */
  retry?: RetryOptions;
}

export interface BodySelectServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Per-call retry policy; overrides the client-level policy. */
  retry?: RetryOptions;
}

export class BodySelectServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;
  private retry?: RetryOptions;

  constructor(baseURL: string, options?: BodySelectServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    this.retry = options?.retry;
  }

  async updateProfile(req: UpdateProfileRequest, options?: BodySelectServiceCallOptions): Promise<Profile> {
    let path = "/api/v1/users/{user_id}/profile";
    path = path.replace("{user_id}", encodeURIComponent(String(req.userId)));
    const params = new URLSearchParams();
    if (req.notify) params.set("notify", String(req.notify));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "PUT",
      headers,
      body: JSON.stringify(req.profile ?? {}),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Profile;
  }

  async createNote(req: CreateNoteRequest, options?: BodySelectServiceCallOptions): Promise<Note> {
    let path = "/api/v1/notes";
    const params = new URLSearchParams();
    if (req.collection != null && req.collection !== "") params.set("collection", String(req.collection));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req.note ?? {}),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Note;
  }

  async createProfile(req: CreateProfileRequest, options?: BodySelectServiceCallOptions): Promise<Profile> {
    let path = "/api/v1/profiles";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Profile;
  }

  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {
    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);
    const baseDelayMs = retry?.baseDelayMs ?? 250;
    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];
    let lastError: unknown;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
      try {
        const resp = await this.fetchFn(url, init);
        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {
          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, "");
          continue;
        }
        return resp;
      } catch (e) {
        // Aborts are intentional; never retry them.
        if (e instanceof Error && e.name === "AbortError") throw e;
        lastError = e;
      }
    }
    throw lastError;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

