// Code generated by protoc-gen-onekit-ts-client. DO NOT EDIT.
// source: http_verbs_comprehensive.proto

export interface ListResourcesRequest {
  page: number;
  pageSize: number;
  filter: string;
  includeDeleted: boolean;
  sinceTimestamp: string;
  maxId: string;
  minScore: number;
  maxScore: number;
}

export interface ListResourcesResponse {
  resources: Resource[];
  totalCount: number;
  page: number;
}

export interface Resource {
  id: string;
  name: string;
  description: string;
  metadata: Record<string, string>;
  createdAt: string;
  updatedAt: string;
  status: ResourceStatus;
  metadataDetail?: ResourceMetadata;
  tag?: string;
}

export interface ResourceMetadata {
  createdBy: string;
  createdAtUnix: string;
  version: number;
}

export interface GetResourceRequest {
  resourceId: string;
}

export interface GetNestedResourceRequest {
  orgId: string;
  teamId: string;
  resourceId: string;
}

export interface CreateResourceRequest {
  name: string;
  description: string;
  metadata: Record<string, string>;
}

export interface UpdateResourceRequest {
  resourceId: string;
  name: string;
  description: string;
  metadata: Record<string, string>;
}

export interface PatchResourceRequest {
  resourceId: string;
  name: string;
  description: string;
}

export interface DeleteResourceRequest {
  resourceId: string;
}

export interface DeleteResourceResponse {
  success: boolean;
}

export interface DefaultPostRequest {
  action: string;
}

export interface DefaultPostResponse {
  result: string;
}

export interface SearchResourcesRequest {
  statusFilter: ResourceStatus;
  query: string;
}

export interface LegacyRequest {
  data: string;
}

export interface LegacyResponse {
  result: string;
}

export type ResourceStatus = "RESOURCE_STATUS_UNSPECIFIED" | "RESOURCE_STATUS_ACTIVE" | "RESOURCE_STATUS_INACTIVE" | "RESOURCE_STATUS_ARCHIVED";

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface RetryOptions {
  /** Total number of attempts including the first. Default 1 (no retries). */
  maxAttempts?: number;
  /** Delay before the first retry in milliseconds; doubles each retry. Default 250. */
  baseDelayMs?: number;
  /** Status codes that trigger a retry. Default [429, 502, 503, 504]. */
  retryableStatuses?: number[];
}

export interface RESTfulAPIServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  /** Retry policy for transient failures. Never applied to SSE streams. */
  retry?: RetryOptions;
  apiKey?: string;
}

export interface RESTfulAPIServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Per-call retry policy; overrides the client-level policy. */
  retry?: RetryOptions;
  apiKey?: string;
  requestId?: string;
}

export class RESTfulAPIServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;
  private retry?: RetryOptions;

  constructor(baseURL: string, options?: RESTfulAPIServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    this.retry = options?.retry;
    if (options?.apiKey) {
      this.defaultHeaders["X-API-Key"] = options.apiKey;
    }
  }

  async listResources(req: ListResourcesRequest, options?: RESTfulAPIServiceCallOptions): Promise<ListResourcesResponse> {
    let path = "/api/v1/resources";
    const params = new URLSearchParams();
    if (req.page != null && req.page !== 0) params.set("page", String(req.page));
    if (req.pageSize != null && req.pageSize !== 0) params.set("page_size", String(req.pageSize));
    if (req.filter != null && req.filter !== "") params.set("filter", String(req.filter));
    if (req.includeDeleted) params.set("include_deleted", String(req.includeDeleted));
    if (req.sinceTimestamp != null && req.sinceTimestamp !== "0") params.set("since_timestamp", String(req.sinceTimestamp));
    if (req.maxId != null && req.maxId !== "0") params.set("max_id", String(req.maxId));
    if (req.minScore != null && req.minScore !== 0) params.set("min_score", String(req.minScore));
    if (req.maxScore != null && req.maxScore !== 0) params.set("max_score", String(req.maxScore));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as ListResourcesResponse;
  }

  async getResource(req: GetResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async getNestedResource(req: GetNestedResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/orgs/{org_id}/teams/{team_id}/resources/{resource_id}";
    path = path.replace("{org_id}", encodeURIComponent(String(req.orgId)));
    path = path.replace("{team_id}", encodeURIComponent(String(req.teamId)));
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async createResource(req: CreateResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.requestId) headers["X-Request-ID"] = options.requestId;

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async updateResource(req: UpdateResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "PUT",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async patchResource(req: PatchResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "PATCH",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async deleteResource(req: DeleteResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<DeleteResourceResponse> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "DELETE",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as DeleteResourceResponse;
  }

  async defaultPostMethod(req: DefaultPostRequest, options?: RESTfulAPIServiceCallOptions): Promise<DefaultPostResponse> {
    let path = "/api/v1/legacy/action";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as DefaultPostResponse;
  }

  async searchResources(req: SearchResourcesRequest, options?: RESTfulAPIServiceCallOptions): Promise<ListResourcesResponse> {
    let path = "/api/v1/resources/search";
    const params = new URLSearchParams();
    if (req.statusFilter != null && req.statusFilter !== "RESOURCE_STATUS_UNSPECIFIED") params.set("status", String(req.statusFilter));
    if (req.query != null && req.query !== "") params.set("q", String(req.query));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as ListResourcesResponse;
  }

  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {
    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);
    const baseDelayMs = retry?.baseDelayMs ?? 250;
    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];
    let lastError: unknown;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
      try {
        const resp = await this.fetchFn(url, init);
        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {
          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, "");
          continue;
        }
        return resp;
      } catch (e) {
        // Aborts are intentional; never retry them.
        if (e instanceof Error && e.name === "AbortError") throw e;
        lastError = e;
      }
    }
    throw lastError;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

export interface BackwardCompatServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  /** Retry policy for transient failures. Never applied to SSE streams. */
  retry?: RetryOptions;
}

export interface BackwardCompatServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Per-call retry policy; overrides the client-level policy. */
  retry?: RetryOptions;
}

export class BackwardCompatServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;
  private retry?: RetryOptions;

  constructor(baseURL: string, options?: BackwardCompatServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    this.retry = options?.retry;
  }

  async legacyAction(req: LegacyRequest, options?: BackwardCompatServiceCallOptions): Promise<LegacyResponse> {
    let path = "/legacyAction";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as LegacyResponse;
  }

  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {
    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);
    const baseDelayMs = retry?.baseDelayMs ?? 250;
    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];
    let lastError: unknown;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
      try {
        const resp = await this.fetchFn(url, init);
        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {
          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, "");
          continue;
        }
        return resp;
      } catch (e) {
        // Aborts are intentional; never retry them.
        if (e instanceof Error && e.name === "AbortError") throw e;
        lastError = e;
      }
    }
    throw lastError;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

