// Code generated by protoc-gen-onekit-ts-client. DO NOT EDIT.
// source: query_params.proto

export interface SearchWithTypesRequest {
  query: string;
  limit: number;
  offset: string;
  active: boolean;
  minScore: number;
  maxScore: number;
  page: number;
  timestamp: string;
}

export interface SearchResponse {
  results: string[];
  total: number;
}

export interface SearchRequiredRequest {
  query: string;
  page: number;
  pageSize: number;
}

export interface SearchCustomNamesRequest {
  searchTerm: string;
  resultsPerPage: number;
  pageNumber: number;
  sortField: string;
  descendingOrder: boolean;
}

export interface GetWithFiltersRequest {
  resourceId: string;
  filter: string;
  limit: number;
}

export interface SearchAdvancedRequest {
  region: Region;
  countries: string[];
  keyword: string;
  years: number[];
  flags: boolean[];
  regions: Region[];
}

export interface GetByRegionRequest {
  region: Region;
  keyword: string;
}

export interface EmptyRequest {
}

export type Region = "unspecified" | "americas" | "europe" | "asia";

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface RetryOptions {
  /** Total number of attempts including the first. Default 1 (no retries). */
  maxAttempts?: number;
  /** Delay before the first retry in milliseconds; doubles each retry. Default 250. */
  baseDelayMs?: number;
  /** Status codes that trigger a retry. Default [429, 502, 503, 504]. */
  retryableStatuses?: number[];
}

export interface QueryParamServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  /** Retry policy for transient failures. Never applied to SSE streams. */
  retry?: RetryOptions;
}

export interface QueryParamServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Per-call retry policy; overrides the client-level policy. */
  retry?: RetryOptions;
}

export class QueryParamServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;
  private retry?: RetryOptions;

  constructor(baseURL: string, options?: QueryParamServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    this.retry = options?.retry;
  }

  async searchWithTypes(req: SearchWithTypesRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/search/typed";
    const params = new URLSearchParams();
    if (req.query != null && req.query !== "") params.set("q", String(req.query));
    if (req.limit != null && req.limit !== 0) params.set("limit", String(req.limit));
    if (req.offset != null && req.offset !== "0") params.set("offset", String(req.offset));
    if (req.active) params.set("active", String(req.active));
    if (req.minScore != null && req.minScore !== 0) params.set("min_score", String(req.minScore));
    if (req.maxScore != null && req.maxScore !== 0) params.set("max_score", String(req.maxScore));
    if (req.page != null && req.page !== 0) params.set("page", String(req.page));
    if (req.timestamp != null && req.timestamp !== "0") params.set("ts", String(req.timestamp));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  async searchRequired(req: SearchRequiredRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/search/required";
    const params = new URLSearchParams();
    if (req.query != null && req.query !== "") params.set("q", String(req.query));
    if (req.page != null && req.page !== 0) params.set("page", String(req.page));
    if (req.pageSize != null && req.pageSize !== 0) params.set("page_size", String(req.pageSize));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  async searchCustomNames(req: SearchCustomNamesRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/search/custom";
    const params = new URLSearchParams();
    if (req.searchTerm != null && req.searchTerm !== "") params.set("q", String(req.searchTerm));
    if (req.resultsPerPage != null && req.resultsPerPage !== 0) params.set("limit", String(req.resultsPerPage));
    if (req.pageNumber != null && req.pageNumber !== 0) params.set("page", String(req.pageNumber));
    if (req.sortField != null && req.sortField !== "") params.set("sort", String(req.sortField));
    if (req.descendingOrder) params.set("desc", String(req.descendingOrder));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  async getWithFilters(req: GetWithFiltersRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/resources/{resource_id}/items";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const params = new URLSearchParams();
    if (req.filter != null && req.filter !== "") params.set("filter", String(req.filter));
    if (req.limit != null && req.limit !== 0) params.set("limit", String(req.limit));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  async searchAdvanced(req: SearchAdvancedRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/search/advanced";
    const params = new URLSearchParams();
    if (req.region != null && req.region !== "unspecified") params.set("region", String(req.region));
    if (req.countries && req.countries.length > 0) req.countries.forEach(v => params.append("countries", String(v)));
    if (req.keyword != null && req.keyword !== "") params.set("keyword", String(req.keyword));
    if (req.years && req.years.length > 0) req.years.forEach(v => params.append("years", String(v)));
    if (req.flags && req.flags.length > 0) req.flags.forEach(v => params.append("flags", String(v)));
    if (req.regions && req.regions.length > 0) req.regions.forEach(v => params.append("regions", String(v)));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  async getByRegion(req: GetByRegionRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/regions/{region}";
    path = path.replace("{region}", encodeURIComponent(String(req.region)));
    const params = new URLSearchParams();
    if (req.keyword != null && req.keyword !== "") params.set("keyword", String(req.keyword));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  async getDefaults(_req: EmptyRequest, options?: QueryParamServiceCallOptions): Promise<SearchResponse> {
    let path = "/api/defaults";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as SearchResponse;
  }

  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {
    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);
    const baseDelayMs = retry?.baseDelayMs ?? 250;
    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];
    let lastError: unknown;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
      try {
        const resp = await this.fetchFn(url, init);
        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {
          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, "");
          continue;
        }
        return resp;
      } catch (e) {
        // Aborts are intentional; never retry them.
        if (e instanceof Error && e.name === "AbortError") throw e;
        lastError = e;
      }
    }
    throw lastError;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

