// Code generated by protoc-gen-onekit-ts-client. DO NOT EDIT.
// source: unwrap.proto

export interface GetOptionBarsRequest {
  symbols: string[];
  startDate: string;
  endDate: string;
}

export interface GetOptionBarsResponse {
  bars: Record<string, OptionBar[]>;
  nextPageToken: string;
}

export interface OptionBarsList {
  bars: OptionBar[];
}

export interface OptionBar {
  symbol: string;
  price: number;
  volume: string;
  timestamp: string;
}

export interface RootMapResponse {
  people: Record<string, OptionBar>;
}

export interface RootRepeatedResponse {
  items: OptionBar[];
}

export interface RootMapWithValueUnwrapResponse {
  data: Record<string, OptionBar[]>;
}

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface RetryOptions {
  /** Total number of attempts including the first. Default 1 (no retries). */
  maxAttempts?: number;
  /** Delay before the first retry in milliseconds; doubles each retry. Default 250. */
  baseDelayMs?: number;
  /** Status codes that trigger a retry. Default [429, 502, 503, 504]. */
  retryableStatuses?: number[];
}

export interface OptionDataServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  /** Retry policy for transient failures. Never applied to SSE streams. */
  retry?: RetryOptions;
}

export interface OptionDataServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Per-call retry policy; overrides the client-level policy. */
  retry?: RetryOptions;
}

export class OptionDataServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;
  private retry?: RetryOptions;

  constructor(baseURL: string, options?: OptionDataServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    this.retry = options?.retry;
  }

  async getOptionBars(req: GetOptionBarsRequest, options?: OptionDataServiceCallOptions): Promise<GetOptionBarsResponse> {
    let path = "/api/v1/options/bars";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as GetOptionBarsResponse;
  }

  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {
    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);
    const baseDelayMs = retry?.baseDelayMs ?? 250;
    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];
    let lastError: unknown;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
      try {
        const resp = await this.fetchFn(url, init);
        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {
          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, "");
          continue;
        }
        return resp;
      } catch (e) {
        // Aborts are intentional; never retry them.
        if (e instanceof Error && e.name === "AbortError") throw e;
        lastError = e;
      }
    }
    throw lastError;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

export interface UnwrapServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  /** Retry policy for transient failures. Never applied to SSE streams. */
  retry?: RetryOptions;
}

export interface UnwrapServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Per-call retry policy; overrides the client-level policy. */
  retry?: RetryOptions;
}

export class UnwrapServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;
  private retry?: RetryOptions;

  constructor(baseURL: string, options?: UnwrapServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    this.retry = options?.retry;
  }

  async getOptionBars(req: GetOptionBarsRequest, options?: UnwrapServiceCallOptions): Promise<GetOptionBarsResponse> {
    let path = "/api/v1/options/bars";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as GetOptionBarsResponse;
  }

  async getRootMap(req: GetOptionBarsRequest, options?: UnwrapServiceCallOptions): Promise<Record<string, OptionBar>> {
    let path = "/api/v1/root/map";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Record<string, OptionBar>;
  }

  async getRootRepeated(req: GetOptionBarsRequest, options?: UnwrapServiceCallOptions): Promise<OptionBar[]> {
    let path = "/api/v1/root/repeated";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as OptionBar[];
  }

  async getRootMapWithValueUnwrap(req: GetOptionBarsRequest, options?: UnwrapServiceCallOptions): Promise<Record<string, OptionBar[]>> {
    let path = "/api/v1/root/map-value-unwrap";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.doFetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    }, options?.retry ?? this.retry);

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Record<string, OptionBar[]>;
  }

  private async doFetch(url: string, init: RequestInit, retry?: RetryOptions): Promise<Response> {
    const maxAttempts = Math.max(1, retry?.maxAttempts ?? 1);
    const baseDelayMs = retry?.baseDelayMs ?? 250;
    const retryableStatuses = retry?.retryableStatuses ?? [429, 502, 503, 504];
    let lastError: unknown;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, baseDelayMs * 2 ** (attempt - 1)));
      }
      try {
        const resp = await this.fetchFn(url, init);
        if (attempt < maxAttempts - 1 && retryableStatuses.includes(resp.status)) {
          lastError = new ApiError(resp.status, `Request failed with retryable status ${resp.status}`, "");
          continue;
        }
        return resp;
      } catch (e) {
        // Aborts are intentional; never retry them.
        if (e instanceof Error && e.name === "AbortError") throw e;
        lastError = e;
      }
    }
    throw lastError;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

