package genpy

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

const pyNone = "None"

func pyDefaultValue(t *onkir.Type) string {
	if t == nil {
		return pyNone
	}
	switch t.Kind {
	case onkir.KindScalar:
		switch t.Scalar {
		case onkir.ScalarString, onkir.ScalarTimestamp:
			return `""`
		case onkir.ScalarBool:
			return "False"
		case onkir.ScalarInt32, onkir.ScalarInt64, onkir.ScalarUint32, onkir.ScalarUint64:
			return "0"
		case onkir.ScalarFloat32, onkir.ScalarFloat64:
			return "0.0"
		case onkir.ScalarBytes:
			return `b""`
		default:
			return pyNone
		}
	case onkir.KindMessage, onkir.KindEnum, onkir.KindMap:
		return pyNone
	default:
		return pyNone
	}
}

func GenerateTypes(file *onkir.File) []byte {
	p := &Printer{}
	p.P("# Code generated by onek. DO NOT EDIT.")
	p.P("from __future__ import annotations")
	p.P()
	p.P("from dataclasses import dataclass, field")
	p.P("from enum import IntEnum")
	p.P()

	for _, e := range file.Enums {
		writeEnum(p, e)
	}
	for _, m := range file.Messages {
		if m.IsError() {
			writeErrorClass(p, m)
		} else {
			writeMessage(p, m)
		}
	}

	return p.Bytes()
}

func writeEnum(p *Printer, e *onkir.Enum) {
	p.P("class ", e.Name, "(IntEnum):")
	p.Indent()
	for i, v := range e.Values {
		p.P(v.Name, " = ", strconv.Itoa(i))
	}
	p.Dedent()
	p.Blank()
}

func writeFieldDecl(p *Printer, f *onkir.Field) {
	if f.Oneof != nil {
		p.P(f.Name, ": dict | None = None")
		return
	}
	pyType := PyFieldType(f.Type)
	switch {
	case f.Repeated:
		p.P(f.Name, ": list[", pyType, "] = field(default_factory=list)")
	case f.Type.Kind == onkir.KindMap:
		p.P(f.Name, ": ", pyType, " = field(default_factory=dict)")
	case f.Optional || f.Type.Kind == onkir.KindMessage:
		p.P(f.Name, ": ", pyType, " | None = None")
	default:
		p.P(f.Name, ": ", pyType, " = ", pyDefaultValue(f.Type))
	}
}

func writeToDictField(p *Printer, f *onkir.Field) {
	if f.Oneof != nil {
		p.P("if self.", f.Name, " is not None:")
		p.Indent()
		p.P("d[", fmt.Sprintf("%q", f.Name), "] = dict(self.", f.Name, ")")
		p.Dedent()
		return
	}
	switch {
	case f.Repeated:
		if f.Type.Kind == onkir.KindMessage {
			p.P("if self.", f.Name, ":")
			p.Indent()
			p.P("d[", fmt.Sprintf("%q", f.Name), "] = [v.to_dict() for v in self.", f.Name, "]")
			p.Dedent()
		} else {
			p.P("if self.", f.Name, ":")
			p.Indent()
			p.P("d[", fmt.Sprintf("%q", f.Name), "] = list(self.", f.Name, ")")
			p.Dedent()
		}
	case f.Type.Kind == onkir.KindMap:
		p.P("if self.", f.Name, ":")
		p.Indent()
		if f.Type.MapValue.Kind == onkir.KindMessage {
			p.P("d[", fmt.Sprintf("%q", f.Name), "] = {k: v.to_dict() for k, v in self.", f.Name, ".items()}")
		} else {
			p.P("d[", fmt.Sprintf("%q", f.Name), "] = dict(self.", f.Name, ")")
		}
		p.Dedent()
	case f.Type.Kind == onkir.KindMessage:
		p.P("if self.", f.Name, " is not None:")
		p.Indent()
		p.P("d[", fmt.Sprintf("%q", f.Name), "] = self.", f.Name, ".to_dict()")
		p.Dedent()
	case f.Type.Kind == onkir.KindEnum:
		p.P("if self.", f.Name, " is not None:")
		p.Indent()
		p.P("d[", fmt.Sprintf("%q", f.Name), "] = int(self.", f.Name, ")")
		p.Dedent()
	case f.Optional:
		p.P("if self.", f.Name, " is not None:")
		p.Indent()
		p.P("d[", fmt.Sprintf("%q", f.Name), "] = self.", f.Name)
		p.Dedent()
	default:
		p.P("d[", fmt.Sprintf("%q", f.Name), "] = self.", f.Name)
	}
}

func writeFromDictField(f *onkir.Field) string {
	key := fmt.Sprintf("%q", f.Name)
	if f.Oneof != nil {
		return fmt.Sprintf("d.get(%s)", key)
	}
	switch {
	case f.Repeated:
		if f.Type.Kind == onkir.KindMessage {
			return fmt.Sprintf("[%s.from_dict(v) for v in d.get(%s, [])]", f.Type.Message.Name, key)
		}
		return fmt.Sprintf("list(d.get(%s, []))", key)
	case f.Type.Kind == onkir.KindMap:
		if f.Type.MapValue.Kind == onkir.KindMessage {
			return fmt.Sprintf(
				"{k: %s.from_dict(v) for k, v in d.get(%s, {}).items()}",
				f.Type.MapValue.Message.Name, key,
			)
		}
		return fmt.Sprintf("dict(d.get(%s, {}))", key)
	case f.Type.Kind == onkir.KindMessage:
		return fmt.Sprintf("(%s.from_dict(d[%s]) if d.get(%s) is not None else None)", f.Type.Message.Name, key, key)
	case f.Type.Kind == onkir.KindEnum:
		return fmt.Sprintf("(%s(d[%s]) if d.get(%s) is not None else None)", f.Type.Enum.Name, key, key)
	case f.Optional:
		return fmt.Sprintf("d.get(%s)", key)
	default:
		return fmt.Sprintf("d.get(%s, %s)", key, pyDefaultValue(f.Type))
	}
}

func writeMessage(p *Printer, m *onkir.Message) {
	p.P("@dataclass")
	p.P("class ", m.Name, ":")
	p.Indent()
	if len(m.Fields) == 0 {
		p.P("pass")
	}
	for _, f := range m.Fields {
		writeFieldDecl(p, f)
	}
	p.Blank()

	p.P("def to_dict(self) -> dict:")
	p.Indent()
	p.P("d: dict = {}")
	for _, f := range m.Fields {
		writeToDictField(p, f)
	}
	p.P("return d")
	p.Dedent()
	p.Blank()

	p.P("@staticmethod")
	p.P("def from_dict(d: dict) -> ", fmt.Sprintf("%q", m.Name), ":")
	p.Indent()
	p.P("return ", m.Name, "(")
	p.Indent()
	for _, f := range m.Fields {
		p.P(f.Name, "=", writeFromDictField(f), ",")
	}
	p.Dedent()
	p.P(")")
	p.Dedent()
	p.Dedent()
	p.Blank()

	for _, nested := range m.Nested {
		if nested.IsError() {
			writeErrorClass(p, nested)
		} else {
			writeMessage(p, nested)
		}
	}
	for _, nested := range m.NestedEnums {
		writeEnum(p, nested)
	}
}

func writeErrorClass(p *Printer, m *onkir.Message) {
	p.P("class ", m.Name, "(Exception):")
	p.Indent()
	p.P("def __init__(self", errorInitArgs(m), ") -> None:")
	p.Indent()
	for _, f := range m.Fields {
		p.P("self.", f.Name, " = ", f.Name)
	}
	parts := make([]string, len(m.Fields))
	for i, f := range m.Fields {
		parts[i] = fmt.Sprintf("%s={self.%s!r}", f.Name, f.Name)
	}
	p.P(fmt.Sprintf("super().__init__(f%q)", m.Name+" "+strings.Join(parts, " ")))
	p.Dedent()
	p.Blank()

	p.P("def to_dict(self) -> dict:")
	p.Indent()
	p.P("d: dict = {}")
	for _, f := range m.Fields {
		writeToDictField(p, f)
	}
	p.P("return d")
	p.Dedent()
	p.Blank()

	p.P("@staticmethod")
	p.P("def from_dict(d: dict) -> ", fmt.Sprintf("%q", m.Name), ":")
	p.Indent()
	p.P("return ", m.Name, "(")
	p.Indent()
	for _, f := range m.Fields {
		p.P(f.Name, "=", writeFromDictField(f), ",")
	}
	p.Dedent()
	p.P(")")
	p.Dedent()
	p.Dedent()
	p.Blank()
}

func errorInitArgs(m *onkir.Message) string {
	var sb strings.Builder
	for _, f := range m.Fields {
		sb.WriteString(", ")
		sb.WriteString(f.Name)
		sb.WriteString(": ")
		pyType := PyFieldType(f.Type)
		if f.Repeated {
			pyType = "list[" + pyType + "]"
		}
		sb.WriteString(pyType)
		sb.WriteString(" = ")
		sb.WriteString(pyDefaultValue(f.Type))
	}
	return sb.String()
}
