// Code generated by protoc-gen-onekit-go-client. DO NOT EDIT.
// source: complex_features.proto

package generated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	onekithttp "github.com/1homsi/onekit/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// onekitUnmarshaler is implemented by generated messages with custom JSON unmarshaling.
// It allows passing protojson.UnmarshalOptions (e.g. DiscardUnknown) through custom unmarshalers.
type onekitUnmarshaler interface {
	UnmarshalJSONOnekit(data []byte, opts protojson.UnmarshalOptions) error
}

// onekitIsRetryableStatus reports whether a status code is safe to retry:
// 429 Too Many Requests, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout.
func onekitIsRetryableStatus(status int) bool {
	switch status {
	case http.StatusTooManyRequests,
		http.StatusBadGateway,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		return true
	}
	return false
}

// FeatureServiceClient is the client API for FeatureService service.
type FeatureServiceClient interface {
	ListNotes(ctx context.Context, req *ListNotesRequest, opts ...FeatureServiceCallOption) (*ListNotesResponse, error)
	GetNote(ctx context.Context, req *GetNoteRequest, opts ...FeatureServiceCallOption) (*Note, error)
	CreateNote(ctx context.Context, req *CreateNoteRequest, opts ...FeatureServiceCallOption) (*Note, error)
	UpdateNote(ctx context.Context, req *UpdateNoteRequest, opts ...FeatureServiceCallOption) (*Note, error)
	GetNoteList(ctx context.Context, req *GetNoteListRequest, opts ...FeatureServiceCallOption) (*NoteList, error)
	GetNoteMap(ctx context.Context, req *GetNoteMapRequest, opts ...FeatureServiceCallOption) (*NoteMap, error)
	GetBarsBySymbol(ctx context.Context, req *GetBarsBySymbolRequest, opts ...FeatureServiceCallOption) (*BarsBySymbol, error)
	GetCombinedUnwrap(ctx context.Context, req *GetCombinedUnwrapRequest, opts ...FeatureServiceCallOption) (*CombinedUnwrap, error)
}

// featureServiceClient is the implementation of FeatureServiceClient.
type featureServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
	retryMaxAttempts     int
	retryBackoff         time.Duration
}

var _ FeatureServiceClient = (*featureServiceClient)(nil)

// FeatureServiceClientOption configures a FeatureService client.
type FeatureServiceClientOption func(*featureServiceClient)

// WithFeatureServiceHTTPClient sets the HTTP client to use for requests.
func WithFeatureServiceHTTPClient(client *http.Client) FeatureServiceClientOption {
	return func(c *featureServiceClient) {
		c.httpClient = client
	}
}

// WithFeatureServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithFeatureServiceContentType(contentType string) FeatureServiceClientOption {
	return func(c *featureServiceClient) {
		c.contentType = contentType
	}
}

// WithFeatureServiceDefaultHeader sets a default header to include in all requests.
func WithFeatureServiceDefaultHeader(key, value string) FeatureServiceClientOption {
	return func(c *featureServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithFeatureServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithFeatureServiceDiscardUnknownFields(discard bool) FeatureServiceClientOption {
	return func(c *featureServiceClient) {
		c.discardUnknownFields = discard
	}
}

// WithFeatureServiceRetry enables automatic retries for transient failures.
// maxAttempts is the total number of attempts including the first (values < 1 disable retries).
// baseBackoff is the delay before the first retry; it doubles on each subsequent retry.
// Retried failures: transport errors and HTTP 429, 502, 503, 504. SSE streams are never retried.
func WithFeatureServiceRetry(maxAttempts int, baseBackoff time.Duration) FeatureServiceClientOption {
	return func(c *featureServiceClient) {
		c.retryMaxAttempts = maxAttempts
		c.retryBackoff = baseBackoff
	}
}

// FeatureServiceCallOption configures a single RPC call.
type FeatureServiceCallOption func(*featureServiceCallOptions)

// featureServiceCallOptions holds options for a single RPC call.
type featureServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithFeatureServiceHeader adds a header to a single request.
func WithFeatureServiceHeader(key, value string) FeatureServiceCallOption {
	return func(o *featureServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithFeatureServiceCallContentType sets the content type for a single request.
func WithFeatureServiceCallContentType(contentType string) FeatureServiceCallOption {
	return func(o *featureServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithFeatureServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithFeatureServiceDiscardUnknownFields.
func WithFeatureServiceCallDiscardUnknownFields(discard bool) FeatureServiceCallOption {
	return func(o *featureServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// WithFeatureServiceAPIKey API authentication key
func WithFeatureServiceAPIKey(value string) FeatureServiceClientOption {
	return WithFeatureServiceDefaultHeader("X-API-Key", value)
}

// WithFeatureServiceCallAPIKey API authentication key for a single request.
func WithFeatureServiceCallAPIKey(value string) FeatureServiceCallOption {
	return WithFeatureServiceHeader("X-API-Key", value)
}

// WithFeatureServiceTenantID Tenant identifier
func WithFeatureServiceTenantID(value string) FeatureServiceClientOption {
	return WithFeatureServiceDefaultHeader("X-Tenant-ID", value)
}

// WithFeatureServiceCallTenantID Tenant identifier for a single request.
func WithFeatureServiceCallTenantID(value string) FeatureServiceCallOption {
	return WithFeatureServiceHeader("X-Tenant-ID", value)
}

// WithFeatureServiceCallRequestID sets the X-Request-ID header for a single request.
func WithFeatureServiceCallRequestID(value string) FeatureServiceCallOption {
	return WithFeatureServiceHeader("X-Request-ID", value)
}

// WithFeatureServiceCallIdempotencyKey sets the X-Idempotency-Key header for a single request.
func WithFeatureServiceCallIdempotencyKey(value string) FeatureServiceCallOption {
	return WithFeatureServiceHeader("X-Idempotency-Key", value)
}

// NewFeatureServiceClient creates a new FeatureService client.
func NewFeatureServiceClient(baseURL string, opts ...FeatureServiceClientOption) FeatureServiceClient {
	c := &featureServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// ListNotes calls the ListNotes RPC.
func (c *featureServiceClient) ListNotes(ctx context.Context, req *ListNotesRequest, opts ...FeatureServiceCallOption) (*ListNotesResponse, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/notes"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.Page != 0 {
		queryParams.Set("page", fmt.Sprint(req.Page))
	}
	if req.PageSize != 0 {
		queryParams.Set("page_size", fmt.Sprint(req.PageSize))
	}
	if req.Filter != "" {
		queryParams.Set("filter", fmt.Sprint(req.Filter))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &ListNotesResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetNote calls the GetNote RPC.
func (c *featureServiceClient) GetNote(ctx context.Context, req *GetNoteRequest, opts ...FeatureServiceCallOption) (*Note, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/notes/{note_id}"
	path = strings.Replace(path, "{note_id}", url.PathEscape(fmt.Sprint(req.NoteId)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Note{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// CreateNote calls the CreateNote RPC.
func (c *featureServiceClient) CreateNote(ctx context.Context, req *CreateNoteRequest, opts ...FeatureServiceCallOption) (*Note, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/notes"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Note{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// UpdateNote calls the UpdateNote RPC.
func (c *featureServiceClient) UpdateNote(ctx context.Context, req *UpdateNoteRequest, opts ...FeatureServiceCallOption) (*Note, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/notes/{note_id}"
	path = strings.Replace(path, "{note_id}", url.PathEscape(fmt.Sprint(req.NoteId)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "PUT", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Note{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetNoteList calls the GetNoteList RPC.
func (c *featureServiceClient) GetNoteList(ctx context.Context, req *GetNoteListRequest, opts ...FeatureServiceCallOption) (*NoteList, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/notes/list"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &NoteList{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetNoteMap calls the GetNoteMap RPC.
func (c *featureServiceClient) GetNoteMap(ctx context.Context, req *GetNoteMapRequest, opts ...FeatureServiceCallOption) (*NoteMap, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/notes/map"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &NoteMap{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetBarsBySymbol calls the GetBarsBySymbol RPC.
func (c *featureServiceClient) GetBarsBySymbol(ctx context.Context, req *GetBarsBySymbolRequest, opts ...FeatureServiceCallOption) (*BarsBySymbol, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/bars"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &BarsBySymbol{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetCombinedUnwrap calls the GetCombinedUnwrap RPC.
func (c *featureServiceClient) GetCombinedUnwrap(ctx context.Context, req *GetCombinedUnwrapRequest, opts ...FeatureServiceCallOption) (*CombinedUnwrap, error) {
	callOpts := &featureServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/bars/combined"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &CombinedUnwrap{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *featureServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *featureServiceClient) doRequest(httpReq *http.Request) (*http.Response, error) {
	maxAttempts := c.retryMaxAttempts
	if maxAttempts < 1 {
		maxAttempts = 1
	}
	baseBackoff := c.retryBackoff
	if baseBackoff <= 0 {
		baseBackoff = 250 * time.Millisecond
	}

	var lastErr error
	for attempt := 0; attempt < maxAttempts; attempt++ {
		if attempt > 0 {
			backoff := baseBackoff << (attempt - 1)
			select {
			case <-httpReq.Context().Done():
				return nil, httpReq.Context().Err()
			case <-time.After(backoff):
			}
			if httpReq.GetBody != nil {
				newBody, bodyErr := httpReq.GetBody()
				if bodyErr != nil {
					return nil, fmt.Errorf("failed to rewind request body for retry: %w", bodyErr)
				}
				httpReq.Body = newBody
			}
		}

		resp, err := c.httpClient.Do(httpReq)
		if err != nil {
			lastErr = err
			continue
		}
		if attempt < maxAttempts-1 && onekitIsRetryableStatus(resp.StatusCode) {
			_ = resp.Body.Close()
			lastErr = fmt.Errorf("request failed with retryable status %d", resp.StatusCode)
			continue
		}
		return resp, nil
	}
	return nil, lastErr
}

func (c *featureServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &onekithttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &onekithttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *featureServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	opts := protojson.UnmarshalOptions{DiscardUnknown: discardUnknown}

	switch contentType {
	case ContentTypeJSON:
		// Check for onekit-generated custom unmarshaler (passes options through)
		if u, ok := msg.(onekitUnmarshaler); ok {
			return u.UnmarshalJSONOnekit(body, opts)
		}
		// Check for third-party json.Unmarshaler (best effort, cannot pass options)
		if u, ok := msg.(json.Unmarshaler); ok {
			return u.UnmarshalJSON(body)
		}
		return opts.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		return opts.Unmarshal(body, msg)
	}
}
