// Code generated by protoc-gen-onekit-go-client. DO NOT EDIT.
// source: empty_request_body.proto

package emptyrequestbody

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	onekithttp "github.com/1homsi/onekit/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// onekitUnmarshaler is implemented by generated messages with custom JSON unmarshaling.
// It allows passing protojson.UnmarshalOptions (e.g. DiscardUnknown) through custom unmarshalers.
type onekitUnmarshaler interface {
	UnmarshalJSONOnekit(data []byte, opts protojson.UnmarshalOptions) error
}

// onekitIsRetryableStatus reports whether a status code is safe to retry:
// 429 Too Many Requests, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout.
func onekitIsRetryableStatus(status int) bool {
	switch status {
	case http.StatusTooManyRequests, http.StatusBadGateway, http.StatusServiceUnavailable, http.StatusGatewayTimeout:
		return true
	}
	return false
}

// EmptyRequestBodyServiceClient is the client API for EmptyRequestBodyService service.
type EmptyRequestBodyServiceClient interface {
	Ping(ctx context.Context, req *PingRequest, opts ...EmptyRequestBodyServiceCallOption) (*PingResponse, error)
	NoArgs(ctx context.Context, req *NoArgsRequest, opts ...EmptyRequestBodyServiceCallOption) (*NoArgsResponse, error)
}

// emptyRequestBodyServiceClient is the implementation of EmptyRequestBodyServiceClient.
type emptyRequestBodyServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
	retryMaxAttempts     int
	retryBackoff         time.Duration
}

var _ EmptyRequestBodyServiceClient = (*emptyRequestBodyServiceClient)(nil)

// EmptyRequestBodyServiceClientOption configures a EmptyRequestBodyService client.
type EmptyRequestBodyServiceClientOption func(*emptyRequestBodyServiceClient)

// WithEmptyRequestBodyServiceHTTPClient sets the HTTP client to use for requests.
func WithEmptyRequestBodyServiceHTTPClient(client *http.Client) EmptyRequestBodyServiceClientOption {
	return func(c *emptyRequestBodyServiceClient) {
		c.httpClient = client
	}
}

// WithEmptyRequestBodyServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithEmptyRequestBodyServiceContentType(contentType string) EmptyRequestBodyServiceClientOption {
	return func(c *emptyRequestBodyServiceClient) {
		c.contentType = contentType
	}
}

// WithEmptyRequestBodyServiceDefaultHeader sets a default header to include in all requests.
func WithEmptyRequestBodyServiceDefaultHeader(key, value string) EmptyRequestBodyServiceClientOption {
	return func(c *emptyRequestBodyServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithEmptyRequestBodyServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithEmptyRequestBodyServiceDiscardUnknownFields(discard bool) EmptyRequestBodyServiceClientOption {
	return func(c *emptyRequestBodyServiceClient) {
		c.discardUnknownFields = discard
	}
}

// WithEmptyRequestBodyServiceRetry enables automatic retries for transient failures.
// maxAttempts is the total number of attempts including the first (values < 1 disable retries).
// baseBackoff is the delay before the first retry; it doubles on each subsequent retry.
// Retried failures: transport errors and HTTP 429, 502, 503, 504. SSE streams are never retried.
func WithEmptyRequestBodyServiceRetry(maxAttempts int, baseBackoff time.Duration) EmptyRequestBodyServiceClientOption {
	return func(c *emptyRequestBodyServiceClient) {
		c.retryMaxAttempts = maxAttempts
		c.retryBackoff = baseBackoff
	}
}

// EmptyRequestBodyServiceCallOption configures a single RPC call.
type EmptyRequestBodyServiceCallOption func(*emptyRequestBodyServiceCallOptions)

// emptyRequestBodyServiceCallOptions holds options for a single RPC call.
type emptyRequestBodyServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithEmptyRequestBodyServiceHeader adds a header to a single request.
func WithEmptyRequestBodyServiceHeader(key, value string) EmptyRequestBodyServiceCallOption {
	return func(o *emptyRequestBodyServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithEmptyRequestBodyServiceCallContentType sets the content type for a single request.
func WithEmptyRequestBodyServiceCallContentType(contentType string) EmptyRequestBodyServiceCallOption {
	return func(o *emptyRequestBodyServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithEmptyRequestBodyServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithEmptyRequestBodyServiceDiscardUnknownFields.
func WithEmptyRequestBodyServiceCallDiscardUnknownFields(discard bool) EmptyRequestBodyServiceCallOption {
	return func(o *emptyRequestBodyServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewEmptyRequestBodyServiceClient creates a new EmptyRequestBodyService client.
func NewEmptyRequestBodyServiceClient(baseURL string, opts ...EmptyRequestBodyServiceClientOption) EmptyRequestBodyServiceClient {
	c := &emptyRequestBodyServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// Ping calls the Ping RPC.
func (c *emptyRequestBodyServiceClient) Ping(ctx context.Context, req *PingRequest, opts ...EmptyRequestBodyServiceCallOption) (*PingResponse, error) {
	callOpts := &emptyRequestBodyServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/ping"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &PingResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// NoArgs calls the NoArgs RPC.
func (c *emptyRequestBodyServiceClient) NoArgs(ctx context.Context, req *NoArgsRequest, opts ...EmptyRequestBodyServiceCallOption) (*NoArgsResponse, error) {
	callOpts := &emptyRequestBodyServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/no-args"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request (with retries when configured)
	resp, err := c.doRequest(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &NoArgsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *emptyRequestBodyServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *emptyRequestBodyServiceClient) doRequest(httpReq *http.Request) (*http.Response, error) {
	maxAttempts := c.retryMaxAttempts
	if maxAttempts < 1 {
		maxAttempts = 1
	}
	baseBackoff := c.retryBackoff
	if baseBackoff <= 0 {
		baseBackoff = 250 * time.Millisecond
	}

	var lastErr error
	for attempt := 0; attempt < maxAttempts; attempt++ {
		if attempt > 0 {
			backoff := baseBackoff << (attempt - 1)
			select {
			case <-httpReq.Context().Done():
				return nil, httpReq.Context().Err()
			case <-time.After(backoff):
			}
			if httpReq.GetBody != nil {
				newBody, bodyErr := httpReq.GetBody()
				if bodyErr != nil {
					return nil, fmt.Errorf("failed to rewind request body for retry: %w", bodyErr)
				}
				httpReq.Body = newBody
			}
		}

		resp, err := c.httpClient.Do(httpReq)
		if err != nil {
			lastErr = err
			continue
		}
		if attempt < maxAttempts-1 && onekitIsRetryableStatus(resp.StatusCode) {
			_ = resp.Body.Close()
			lastErr = fmt.Errorf("request failed with retryable status %d", resp.StatusCode)
			continue
		}
		return resp, nil
	}
	return nil, lastErr
}

func (c *emptyRequestBodyServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &onekithttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &onekithttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *emptyRequestBodyServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	opts := protojson.UnmarshalOptions{DiscardUnknown: discardUnknown}

	switch contentType {
	case ContentTypeJSON:
		// Check for onekit-generated custom unmarshaler (passes options through)
		if u, ok := msg.(onekitUnmarshaler); ok {
			return u.UnmarshalJSONOnekit(body, opts)
		}
		// Check for third-party json.Unmarshaler (best effort, cannot pass options)
		if u, ok := msg.(json.Unmarshaler); ok {
			return u.UnmarshalJSON(body)
		}
		return opts.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		return opts.Unmarshal(body, msg)
	}
}
