package gengo

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func methodNeedsStrconv(m *onkir.Method) bool {
	for _, field := range m.Request.Fields {
		if _, ok := field.Decorator("query"); !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		if field.Type.Scalar != onkir.ScalarString {
			return true
		}
	}
	return false
}

type clientImports struct {
	bytes, url, strconv, strings, bufio bool
}

func clientImportsNeeded(file *onkir.File) clientImports {
	var imp clientImports
	for _, s := range file.Services {
		for _, m := range s.Methods {
			verb, _ := m.Verb()
			path, _ := m.Path()
			switch {
			case m.IsStream():
				imp.url = true
				imp.strconv = imp.strconv || methodNeedsStrconv(m)
				imp.bufio = true
				imp.strings = true
			case isBodyBearingVerb(verb):
				imp.bytes = true
			default:
				imp.url = true
				imp.strconv = imp.strconv || methodNeedsStrconv(m)
			}
			imp.strings = imp.strings || len(pathParamNames(path)) > 0
		}
	}
	return imp
}

func GenerateClient(file *onkir.File) ([]byte, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}

	imp := clientImportsNeeded(file)
	hasStream := fileHasStreamMethods(file)

	p := &Printer{}
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("package ", GoPackageName(file))
	p.P()
	p.P("import (")
	if imp.bufio {
		p.P(`"bufio"`)
	}
	if imp.bytes {
		p.P(`"bytes"`)
	}
	p.P(`"context"`)
	p.P(`"encoding/json"`)
	p.P(`"fmt"`)
	p.P(`"io"`)
	p.P(`"net/http"`)
	if imp.url {
		p.P(`"net/url"`)
	}
	if imp.strconv {
		p.P(`"strconv"`)
	}
	if imp.strings {
		p.P(`"strings"`)
	}
	p.P(")")
	p.P()

	if hasStream {
		writeEventStreamRuntime(p)
	}

	for _, s := range file.Services {
		writeClientType(p, s)
		for _, m := range s.Methods {
			if m.IsStream() {
				writeSSEClientMethod(p, s, m)
			} else {
				writeClientMethod(p, s, m)
			}
		}
	}

	return p.Format()
}

func writeClientType(p *Printer, s *onkir.Service) {
	p.P("type ", s.Name, "Client struct {")
	p.P("BaseURL string")
	p.P("HTTPClient *http.Client")
	p.P("Headers map[string]string")
	p.P("}")
	p.P()
	p.P("func New", s.Name, "Client(baseURL string) *", s.Name, "Client {")
	p.P("return &", s.Name, "Client{BaseURL: baseURL, HTTPClient: http.DefaultClient, Headers: map[string]string{}}")
	p.P("}")
	p.P()
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := isBodyBearingVerb(verb)

	p.P("func (c *", s.Name, "Client) ", PascalCase(m.Name),
		"(ctx context.Context, req *", m.Request.Name, ") (*", m.Response.Name, ", error) {")

	p.P("path := ", fmt.Sprintf("%q", fullPath))
	for _, paramName := range pathParamNames(path) {
		field := findField(m.Request, paramName)
		if field == nil {
			continue
		}
		p.P("path = strings.ReplaceAll(path, ", fmt.Sprintf("%q", "{"+paramName+"}"), ", ",
			fmt.Sprintf("fmt.Sprintf(%q, req.%s)", "%v", PascalCase(paramName)), ")")
	}

	if bodyBearing {
		p.P("body, err := json.Marshal(req)")
		p.P("if err != nil {")
		p.P(`return nil, fmt.Errorf("marshal request: %w", err)`)
		p.P("}")
	} else {
		writeClientQueryParams(p, m.Request)
	}

	p.P(
		"httpReq, err := http.NewRequestWithContext(ctx, ",
		fmt.Sprintf("%q", strings.ToUpper(verb)), ", c.BaseURL+path, ",
		bodyReaderExpr(bodyBearing), ")",
	)
	p.P("if err != nil {")
	p.P(`return nil, fmt.Errorf("build request: %w", err)`)
	p.P("}")
	if bodyBearing {
		p.P(`httpReq.Header.Set("Content-Type", "application/json")`)
	}
	p.P("for k, v := range c.Headers {")
	p.P("httpReq.Header.Set(k, v)")
	p.P("}")

	p.P("resp, err := c.HTTPClient.Do(httpReq)")
	p.P("if err != nil {")
	p.P(`return nil, fmt.Errorf("do request: %w", err)`)
	p.P("}")
	p.P("defer resp.Body.Close()")
	p.P()

	writeClientErrorHandling(p, m)

	p.P("result := new(", m.Response.Name, ")")
	p.P("if err := json.NewDecoder(resp.Body).Decode(result); err != nil {")
	p.P(`return nil, fmt.Errorf("decode response: %w", err)`)
	p.P("}")
	p.P("return result, nil")
	p.P("}")
	p.P()
}

func bodyReaderExpr(bodyBearing bool) string {
	if bodyBearing {
		return "bytes.NewReader(body)"
	}
	return "nil"
}

func writeClientQueryParams(p *Printer, req *onkir.Message) {
	p.P("query := url.Values{}")
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		goExpr := "req." + PascalCase(field.Name)
		p.P("query.Set(", fmt.Sprintf("%q", queryName), ", ", clientStringifyExpr(field.Type.Scalar, goExpr), ")")
	}
	p.P("if len(query) > 0 {")
	p.P(`path += "?" + query.Encode()`)
	p.P("}")
}

func clientStringifyExpr(kind onkir.ScalarKind, expr string) string {
	switch kind {
	case onkir.ScalarString:
		return expr
	case onkir.ScalarBool:
		return fmt.Sprintf("strconv.FormatBool(%s)", expr)
	case onkir.ScalarInt32, onkir.ScalarInt64:
		return fmt.Sprintf("strconv.FormatInt(int64(%s), 10)", expr)
	case onkir.ScalarUint32, onkir.ScalarUint64:
		return fmt.Sprintf("strconv.FormatUint(uint64(%s), 10)", expr)
	case onkir.ScalarFloat32, onkir.ScalarFloat64:
		return fmt.Sprintf("strconv.FormatFloat(float64(%s), 'f', -1, 64)", expr)
	case onkir.ScalarBytes, onkir.ScalarTimestamp:
		return fmt.Sprintf("fmt.Sprintf(%q, %s)", "%v", expr)
	default:
		return fmt.Sprintf("fmt.Sprintf(%q, %s)", "%v", expr)
	}
}

func writeClientErrorHandling(p *Printer, m *onkir.Method) {
	p.P("if resp.StatusCode < 200 || resp.StatusCode >= 300 {")
	p.P("respBody, _ := io.ReadAll(resp.Body)")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if resp.StatusCode == %d {", status))
		p.P("e := new(", errType.Name, ")")
		p.P("if jsonErr := json.Unmarshal(respBody, e); jsonErr == nil {")
		p.P("return nil, e")
		p.P("}")
		p.P("}")
	}
	p.P(`return nil, fmt.Errorf("unexpected status %d: %s", resp.StatusCode, string(respBody))`)
	p.P("}")
}
