package gengo

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func GoPackageName(file *onkir.File) string {
	parts := strings.Split(file.Package, ".")
	if len(parts) == 0 {
		return "generated"
	}
	return strings.ToLower(parts[len(parts)-1])
}

func needsTimeImport(file *onkir.File) bool {
	for _, m := range file.Messages {
		if messageUsesTime(m) {
			return true
		}
	}
	return false
}

func messageUsesTime(m *onkir.Message) bool {
	for _, f := range m.Fields {
		if f.Type != nil && typeUsesTime(f.Type) {
			return true
		}
	}
	for _, nested := range m.Nested {
		if messageUsesTime(nested) {
			return true
		}
	}
	return false
}

func typeUsesTime(t *onkir.Type) bool {
	switch t.Kind {
	case onkir.KindScalar:
		return t.Scalar == onkir.ScalarTimestamp
	case onkir.KindMap:
		return typeUsesTime(t.MapValue)
	default:
		return false
	}
}

func hasErrorMessages(file *onkir.File) bool {
	for _, m := range file.Messages {
		if messageOrNestedHasError(m) {
			return true
		}
	}
	return false
}

func messageOrNestedHasError(m *onkir.Message) bool {
	if m.IsError() {
		return true
	}
	for _, nested := range m.Nested {
		if messageOrNestedHasError(nested) {
			return true
		}
	}
	return false
}

func GenerateTypes(file *onkir.File) ([]byte, error) {
	p := &Printer{}
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("package ", GoPackageName(file))
	p.P()

	needsTime := needsTimeImport(file)
	needsErrorHelpers := hasErrorMessages(file)
	if needsTime || needsErrorHelpers {
		p.P("import (")
		if needsTime {
			p.P(`"time"`)
		}
		if needsErrorHelpers {
			p.P(`"fmt"`)
			p.P(`"strings"`)
		}
		p.P(")")
		p.P()
	}

	for _, e := range file.Enums {
		writeEnum(p, e)
	}
	for _, m := range file.Messages {
		writeMessage(p, m)
	}

	return p.Format()
}

func writeEnum(p *Printer, e *onkir.Enum) {
	p.P("type ", e.Name, " int32")
	p.P()
	p.P("const (")
	for i, v := range e.Values {
		constName := e.Name + PascalCase(strings.ToLower(v.Name))
		if i == 0 {
			p.P(constName, " ", e.Name, " = iota")
		} else {
			p.P(constName)
		}
	}
	p.P(")")
	p.P()

	p.P("func (v ", e.Name, ") String() string {")
	p.P("switch v {")
	for _, v := range e.Values {
		constName := e.Name + PascalCase(strings.ToLower(v.Name))
		p.P("case ", constName, ":")
		p.P("return ", fmt.Sprintf("%q", v.JSONName()))
	}
	p.P("default:")
	p.P(`return "unknown"`)
	p.P("}")
	p.P("}")
	p.P()
}

func writeMessage(p *Printer, m *onkir.Message) {
	p.P("type ", m.Name, " struct {")
	for _, f := range m.Fields {
		writeField(p, m, f)
	}
	p.P("}")
	p.P()

	if m.IsError() {
		writeErrorMethod(p, m)
	}

	for _, f := range m.Fields {
		if f.Oneof != nil {
			writeOneof(p, m, f)
		}
	}
	for _, nested := range m.Nested {
		writeMessage(p, nested)
	}
	for _, nested := range m.NestedEnums {
		writeEnum(p, nested)
	}
}

func writeErrorMethod(p *Printer, m *onkir.Message) {
	p.P("func (m *", m.Name, ") Error() string {")
	p.P(`parts := []string{"`, m.Name, `"}`)
	for _, f := range m.Fields {
		if f.Oneof != nil {
			continue
		}
		p.P(`parts = append(parts, fmt.Sprintf("`, f.Name, `=%v", m.`, PascalCase(f.Name), "))")
	}
	p.P(`return strings.Join(parts, " ")`)
	p.P("}")
	p.P()
}

func writeField(p *Printer, m *onkir.Message, f *onkir.Field) {
	goName := PascalCase(f.Name)
	if f.Oneof != nil {
		p.P(goName, " ", OneofInterfaceName(m, f), " `json:\"", f.Name, ",omitempty\"`")
		return
	}

	goType := GoFieldType(f.Type)
	if f.Repeated {
		goType = "[]" + goType
	} else if f.Optional && f.Type.Kind != onkir.KindMessage {
		goType = "*" + goType
	}

	p.P(goName, " ", goType, " `json:\"", f.Name, ",omitempty\"`")
}

func writeOneof(p *Printer, m *onkir.Message, f *onkir.Field) {
	iface := OneofInterfaceName(m, f)
	marker := "is" + iface

	p.P("type ", iface, " interface {")
	p.P(marker, "()")
	p.P("}")
	p.P()

	for _, variant := range f.Oneof.Variants {
		typeName := OneofVariantTypeName(m, f, variant)
		p.P("type ", typeName, " struct {")
		p.P(PascalCase(variant.Name), " ", GoFieldType(variant.Type), " `json:\"", variant.Name, ",omitempty\"`")
		p.P("}")
		p.P()
		p.P("func (*", typeName, ") ", marker, "() {}")
		p.P()
	}
}
