// Code generated by protoc-gen-onekit-ts-server. DO NOT EDIT.
// source: body_selection.proto

export interface UpdateProfileRequest {
  userId: string;
  notify: boolean;
  profile?: Profile;
}

export interface Profile {
  displayName: string;
  bio: string;
}

export interface CreateNoteRequest {
  collection: string;
  note?: Note;
}

export interface Note {
  id: string;
  title: string;
  content: string;
}

export interface CreateProfileRequest {
  profile?: Profile;
}

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface ServerContext {
  request: Request;
  pathParams: Record<string, string>;
  headers: Record<string, string>;
}

export interface ServerOptions {
  onError?: (error: unknown, req: Request) => Response | Promise<Response>;
  validateRequest?: (methodName: string, body: unknown) => FieldViolation[] | undefined;
}

export interface RouteDescriptor {
  method: string;
  path: string;
  handler: (req: Request) => Promise<Response>;
}

export interface BodySelectServiceHandler {
  updateProfile(ctx: ServerContext, req: UpdateProfileRequest): Promise<Profile>;
  createNote(ctx: ServerContext, req: CreateNoteRequest): Promise<Note>;
  createProfile(ctx: ServerContext, req: CreateProfileRequest): Promise<Profile>;
}

export function createBodySelectServiceRoutes(
  handler: BodySelectServiceHandler,
  options?: ServerOptions,
): RouteDescriptor[] {
  return [
    {
      method: "PUT",
      path: "/api/v1/users/{user_id}/profile",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const url = new URL(req.url, "http://localhost");
          const pathSegments = url.pathname.split("/");
          pathParams["user_id"] = decodeURIComponent(pathSegments[4] ?? "");

          const body = { profile: await req.json() as Profile } as UpdateProfileRequest;
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("updateProfile", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          body.userId = pathParams["user_id"];

          const params = url.searchParams;
          body.notify = params.get("notify") === "true";

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.updateProfile(ctx, body);
          return new Response(JSON.stringify(result as Profile), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
    {
      method: "POST",
      path: "/api/v1/notes",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const body = { note: await req.json() as Note } as CreateNoteRequest;
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("createNote", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const url = new URL(req.url, "http://localhost");
          const params = url.searchParams;
          body.collection = params.get("collection") ?? "";

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.createNote(ctx, body);
          return new Response(JSON.stringify(result as Note), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
    {
      method: "POST",
      path: "/api/v1/profiles",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const body = await req.json() as CreateProfileRequest;
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("createProfile", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.createProfile(ctx, body);
          return new Response(JSON.stringify(result as Profile), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
  ];
}

