// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/models/portfolio.proto

package models

import (
	_ "github.com/1homsi/onekit/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Timeframe for portfolio data aggregation.
type Timeframe int32

const (
	Timeframe_TIMEFRAME_UNSPECIFIED Timeframe = 0
	Timeframe_TIMEFRAME_1D          Timeframe = 1
	Timeframe_TIMEFRAME_1W          Timeframe = 2
	Timeframe_TIMEFRAME_1M          Timeframe = 3
	Timeframe_TIMEFRAME_3M          Timeframe = 4
	Timeframe_TIMEFRAME_1Y          Timeframe = 5
	Timeframe_TIMEFRAME_ALL         Timeframe = 6
)

// Enum value maps for Timeframe.
var (
	Timeframe_name = map[int32]string{
		0: "TIMEFRAME_UNSPECIFIED",
		1: "TIMEFRAME_1D",
		2: "TIMEFRAME_1W",
		3: "TIMEFRAME_1M",
		4: "TIMEFRAME_3M",
		5: "TIMEFRAME_1Y",
		6: "TIMEFRAME_ALL",
	}
	Timeframe_value = map[string]int32{
		"TIMEFRAME_UNSPECIFIED": 0,
		"TIMEFRAME_1D":          1,
		"TIMEFRAME_1W":          2,
		"TIMEFRAME_1M":          3,
		"TIMEFRAME_3M":          4,
		"TIMEFRAME_1Y":          5,
		"TIMEFRAME_ALL":         6,
	}
)

func (x Timeframe) Enum() *Timeframe {
	p := new(Timeframe)
	*p = x
	return p
}

func (x Timeframe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Timeframe) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_portfolio_proto_enumTypes[0].Descriptor()
}

func (Timeframe) Type() protoreflect.EnumType {
	return &file_proto_models_portfolio_proto_enumTypes[0]
}

func (x Timeframe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Timeframe.Descriptor instead.
func (Timeframe) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_portfolio_proto_rawDescGZIP(), []int{0}
}

// AssetClass categorizes financial instruments.
type AssetClass int32

const (
	AssetClass_ASSET_CLASS_UNSPECIFIED  AssetClass = 0
	AssetClass_ASSET_CLASS_EQUITY       AssetClass = 1
	AssetClass_ASSET_CLASS_FIXED_INCOME AssetClass = 2
	AssetClass_ASSET_CLASS_COMMODITY    AssetClass = 3
	AssetClass_ASSET_CLASS_CRYPTO       AssetClass = 4
)

// Enum value maps for AssetClass.
var (
	AssetClass_name = map[int32]string{
		0: "ASSET_CLASS_UNSPECIFIED",
		1: "ASSET_CLASS_EQUITY",
		2: "ASSET_CLASS_FIXED_INCOME",
		3: "ASSET_CLASS_COMMODITY",
		4: "ASSET_CLASS_CRYPTO",
	}
	AssetClass_value = map[string]int32{
		"ASSET_CLASS_UNSPECIFIED":  0,
		"ASSET_CLASS_EQUITY":       1,
		"ASSET_CLASS_FIXED_INCOME": 2,
		"ASSET_CLASS_COMMODITY":    3,
		"ASSET_CLASS_CRYPTO":       4,
	}
)

func (x AssetClass) Enum() *AssetClass {
	p := new(AssetClass)
	*p = x
	return p
}

func (x AssetClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_portfolio_proto_enumTypes[1].Descriptor()
}

func (AssetClass) Type() protoreflect.EnumType {
	return &file_proto_models_portfolio_proto_enumTypes[1]
}

func (x AssetClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetClass.Descriptor instead.
func (AssetClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_portfolio_proto_rawDescGZIP(), []int{1}
}

// Holding represents a single portfolio holding.
type Holding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AssetClass    AssetClass             `protobuf:"varint,3,opt,name=asset_class,json=assetClass,proto3,enum=examples.enumparams.models.AssetClass" json:"asset_class,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,6,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holding) Reset() {
	*x = Holding{}
	mi := &file_proto_models_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holding) ProtoMessage() {}

func (x *Holding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holding.ProtoReflect.Descriptor instead.
func (*Holding) Descriptor() ([]byte, []int) {
	return file_proto_models_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *Holding) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Holding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holding) GetAssetClass() AssetClass {
	if x != nil {
		return x.AssetClass
	}
	return AssetClass_ASSET_CLASS_UNSPECIFIED
}

func (x *Holding) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Holding) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Holding) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

// PortfolioSummary is the response for portfolio queries.
type PortfolioSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holdings      []*Holding             `protobuf:"bytes,1,rep,name=holdings,proto3" json:"holdings,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	Timeframe     Timeframe              `protobuf:"varint,3,opt,name=timeframe,proto3,enum=examples.enumparams.models.Timeframe" json:"timeframe,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioSummary) Reset() {
	*x = PortfolioSummary{}
	mi := &file_proto_models_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioSummary) ProtoMessage() {}

func (x *PortfolioSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioSummary.ProtoReflect.Descriptor instead.
func (*PortfolioSummary) Descriptor() ([]byte, []int) {
	return file_proto_models_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioSummary) GetHoldings() []*Holding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

func (x *PortfolioSummary) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PortfolioSummary) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *PortfolioSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_models_portfolio_proto protoreflect.FileDescriptor

const file_proto_models_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/models/portfolio.proto\x12\x1aexamples.enumparams.models\x1a\x1donekit/http/annotations.proto\"\xfe\x01\n" +
	"\aHolding\x12\"\n" +
	"\x06symbol\x18\x01 \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04AAPLR\x06symbol\x12$\n" +
	"\x04name\x18\x02 \x01(\tB\x10\xba\xb5\x18\f\n" +
	"\n" +
	"Apple Inc.R\x04name\x12G\n" +
	"\vasset_class\x18\x03 \x01(\x0e2&.examples.enumparams.models.AssetClassR\n" +
	"assetClass\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\x01R\fcurrentPrice\x12\x1f\n" +
	"\vtotal_value\x18\x06 \x01(\x01R\n" +
	"totalValue\"\xcf\x01\n" +
	"\x10PortfolioSummary\x12?\n" +
	"\bholdings\x18\x01 \x03(\v2#.examples.enumparams.models.HoldingR\bholdings\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x01R\n" +
	"totalValue\x12C\n" +
	"\ttimeframe\x18\x03 \x01(\x0e2%.examples.enumparams.models.TimeframeR\ttimeframe\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count*\x93\x01\n" +
	"\tTimeframe\x12\x19\n" +
	"\x15TIMEFRAME_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTIMEFRAME_1D\x10\x01\x12\x10\n" +
	"\fTIMEFRAME_1W\x10\x02\x12\x10\n" +
	"\fTIMEFRAME_1M\x10\x03\x12\x10\n" +
	"\fTIMEFRAME_3M\x10\x04\x12\x10\n" +
	"\fTIMEFRAME_1Y\x10\x05\x12\x11\n" +
	"\rTIMEFRAME_ALL\x10\x06*\x92\x01\n" +
	"\n" +
	"AssetClass\x12\x1b\n" +
	"\x17ASSET_CLASS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ASSET_CLASS_EQUITY\x10\x01\x12\x1c\n" +
	"\x18ASSET_CLASS_FIXED_INCOME\x10\x02\x12\x19\n" +
	"\x15ASSET_CLASS_COMMODITY\x10\x03\x12\x16\n" +
	"\x12ASSET_CLASS_CRYPTO\x10\x04b\x06proto3"

var (
	file_proto_models_portfolio_proto_rawDescOnce sync.Once
	file_proto_models_portfolio_proto_rawDescData []byte
)

func file_proto_models_portfolio_proto_rawDescGZIP() []byte {
	file_proto_models_portfolio_proto_rawDescOnce.Do(func() {
		file_proto_models_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_models_portfolio_proto_rawDesc), len(file_proto_models_portfolio_proto_rawDesc)))
	})
	return file_proto_models_portfolio_proto_rawDescData
}

var file_proto_models_portfolio_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_models_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_models_portfolio_proto_goTypes = []any{
	(Timeframe)(0),           // 0: examples.enumparams.models.Timeframe
	(AssetClass)(0),          // 1: examples.enumparams.models.AssetClass
	(*Holding)(nil),          // 2: examples.enumparams.models.Holding
	(*PortfolioSummary)(nil), // 3: examples.enumparams.models.PortfolioSummary
}
var file_proto_models_portfolio_proto_depIdxs = []int32{
	1, // 0: examples.enumparams.models.Holding.asset_class:type_name -> examples.enumparams.models.AssetClass
	2, // 1: examples.enumparams.models.PortfolioSummary.holdings:type_name -> examples.enumparams.models.Holding
	0, // 2: examples.enumparams.models.PortfolioSummary.timeframe:type_name -> examples.enumparams.models.Timeframe
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_models_portfolio_proto_init() }
func file_proto_models_portfolio_proto_init() {
	if File_proto_models_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_models_portfolio_proto_rawDesc), len(file_proto_models_portfolio_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_models_portfolio_proto_goTypes,
		DependencyIndexes: file_proto_models_portfolio_proto_depIdxs,
		EnumInfos:         file_proto_models_portfolio_proto_enumTypes,
		MessageInfos:      file_proto_models_portfolio_proto_msgTypes,
	}.Build()
	File_proto_models_portfolio_proto = out.File
	file_proto_models_portfolio_proto_goTypes = nil
	file_proto_models_portfolio_proto_depIdxs = nil
}
