// Code generated by onek. DO NOT EDIT.
package api

import (
	"errors"
	"regexp"
	"strings"
)

var emailPattern = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

func inSet(v string, allowed ...string) bool {
	for _, a := range allowed {
		if v == a {
			return true
		}
	}
	return false
}

func (m *User) Validate() error {
	var violations []string
	if m.Id != "" && !uuidPattern.MatchString(m.Id) {
		violations = append(violations, "id must be a valid uuid")
	}
	if len(m.Name) < 1 || len(m.Name) > 100 {
		violations = append(violations, "name must be between 1 and 100 characters")
	}
	if m.Email != "" && !emailPattern.MatchString(m.Email) {
		violations = append(violations, "email must be a valid email")
	}
	if len(violations) > 0 {
		return errors.New(strings.Join(violations, "; "))
	}
	return nil
}

func (m *CreateUserRequest) Validate() error {
	var violations []string
	if len(m.Name) < 2 || len(m.Name) > 100 {
		violations = append(violations, "name must be between 2 and 100 characters")
	}
	if m.Email != "" && !emailPattern.MatchString(m.Email) {
		violations = append(violations, "email must be a valid email")
	}
	if len(violations) > 0 {
		return errors.New(strings.Join(violations, "; "))
	}
	return nil
}

func (m *GetUserRequest) Validate() error {
	var violations []string
	if m.Id != "" && !uuidPattern.MatchString(m.Id) {
		violations = append(violations, "id must be a valid uuid")
	}
	if len(violations) > 0 {
		return errors.New(strings.Join(violations, "; "))
	}
	return nil
}

func (m *EmailAuth) Validate() error {
	var violations []string
	if m.Email != "" && !emailPattern.MatchString(m.Email) {
		violations = append(violations, "email must be a valid email")
	}
	if len(m.Password) < 8 || len(m.Password) > 72 {
		violations = append(violations, "password must be between 8 and 72 characters")
	}
	if len(violations) > 0 {
		return errors.New(strings.Join(violations, "; "))
	}
	return nil
}

func (m *TokenAuth) Validate() error {
	var violations []string
	if len(m.Token) < 10 || len(m.Token) > 256 {
		violations = append(violations, "token must be between 10 and 256 characters")
	}
	if len(violations) > 0 {
		return errors.New(strings.Join(violations, "; "))
	}
	return nil
}

func (m *SocialAuth) Validate() error {
	var violations []string
	if !inSet(m.Provider, "google", "github", "facebook", "apple") {
		violations = append(violations, "provider must be one of the allowed values")
	}
	if len(m.AccessToken) < 20 || len(m.AccessToken) > 512 {
		violations = append(violations, "access_token must be between 20 and 512 characters")
	}
	if len(violations) > 0 {
		return errors.New(strings.Join(violations, "; "))
	}
	return nil
}
