package pyclientgen

// writeTransport emits the HttpTransport Protocol and the stdlib UrllibTransport default.
// The Protocol uses duck typing so users can pass requests/httpx/aiohttp adapters
// without inheriting from any onekit base class.
// When hasSSE is true, UrllibTransport additionally implements stream() for
// Server-Sent Events (see writeSseTransport for the connection types).
func writeTransport(p printer, hasSSE bool) {
	p("@dataclass")
	p("class HttpResponse:")
	p(`    """Minimal HTTP response shape returned by every HttpTransport."""`)
	p("    status: int")
	p("    headers: Mapping[str, str]")
	p("    body: bytes")
	p("")
	p("")
	p("class HttpTransport(Protocol):")
	p(`    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""`)
	p("    def request(")
	p("        self,")
	p("        method: str,")
	p("        url: str,")
	p("        headers: Mapping[str, str],")
	p("        body: Optional[bytes],")
	p("        timeout: Optional[float],")
	p("    ) -> HttpResponse: ...")
	p("")
	p("")
	p("class UrllibTransport:")
	p(`    """Default transport built on the Python standard library."""`)
	p("    def request(")
	p("        self,")
	p("        method: str,")
	p("        url: str,")
	p("        headers: Mapping[str, str],")
	p("        body: Optional[bytes],")
	p("        timeout: Optional[float],")
	p("    ) -> HttpResponse:")
	p("        req = urllib.request.Request(url=url, method=method, data=body)")
	p("        for key, value in headers.items():")
	p("            req.add_header(key, value)")
	p("        try:")
	p("            with urllib.request.urlopen(req, timeout=timeout) as resp:")
	p("                return HttpResponse(")
	p("                    status=resp.status,")
	p("                    headers={k: v for k, v in resp.headers.items()},")
	p("                    body=resp.read(),")
	p("                )")
	p("        except urllib.error.HTTPError as exc:")
	p("            return HttpResponse(")
	p("                status=exc.code,")
	p("                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},")
	p("                body=exc.read() if hasattr(exc, \"read\") else b\"\",")
	p("            )")
	if hasSSE {
		writeUrllibStreamMethod(p)
	}
	p("")
	p("")
}

// writeUrllibStreamMethod emits UrllibTransport.stream(), the SSE streaming
// counterpart of request(). Custom transports opt in to SSE by providing a
// compatible stream() method; clients probe for it with getattr().
func writeUrllibStreamMethod(p printer) {
	p("")
	p("    def stream(")
	p("        self,")
	p("        method: str,")
	p("        url: str,")
	p("        headers: Mapping[str, str],")
	p("        body: Optional[bytes],")
	p("        timeout: Optional[float],")
	p("    ) -> UrllibSseConnection:")
	p(`        """Opens a streaming HTTP connection for Server-Sent Events."""`)
	p("        req = urllib.request.Request(url=url, method=method, data=body)")
	p("        for key, value in headers.items():")
	p("            req.add_header(key, value)")
	p("        try:")
	p("            resp = urllib.request.urlopen(req, timeout=timeout)")
	p("        except urllib.error.HTTPError as exc:")
	p("            return UrllibSseConnection(")
	p("                status=exc.code,")
	p("                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},")
	p("                raw=exc,")
	p("            )")
	p("        return UrllibSseConnection(")
	p("            status=resp.status,")
	p("            headers={k: v for k, v in resp.headers.items()},")
	p("            raw=resp,")
	p("        )")
}

// writeSseTransport emits the SSE connection types and the module-level SSE frame
// parser. Only emitted when the file has stream=true methods.
func writeSseTransport(p printer) {
	p("class SseConnection(Protocol):")
	p(`    """An open Server-Sent Events connection returned by a transport's stream()."""`)
	p("    status: int")
	p("    headers: Mapping[str, str]")
	p("    def iter_lines(self) -> Iterator[bytes]: ...")
	p("    def read_body(self) -> bytes: ...")
	p("    def close(self) -> None: ...")
	p("")
	p("")
	p("class UrllibSseConnection:")
	p(`    """SseConnection over an open urllib response."""`)
	p("    def __init__(self, status: int, headers: Mapping[str, str], raw: Any) -> None:")
	p("        self.status = status")
	p("        self.headers = headers")
	p("        self._raw = raw")
	p("")
	p("    def iter_lines(self) -> Iterator[bytes]:")
	p("        for line in self._raw:")
	p("            yield line")
	p("")
	p("    def read_body(self) -> bytes:")
	p("        return self._raw.read()")
	p("")
	p("    def close(self) -> None:")
	p("        self._raw.close()")
	p("")
	p("")
	p("def _iter_sse_data(lines: Iterator[bytes]) -> Iterator[str]:")
	p(`    """Yields each SSE event's data payload; joins multi-line data fields per spec."""`)
	p("    data_parts: list[str] = []")
	p("    for raw in lines:")
	p(`        line = raw.decode("utf-8").rstrip("\n").rstrip("\r")`)
	p(`        if line == "":`)
	p("            if data_parts:")
	p(`                yield "\n".join(data_parts)`)
	p("                data_parts = []")
	p("            continue")
	p(`        if line.startswith("data:"):`)
	p(`            data_parts.append(line[5:].lstrip(" "))`)
	p("    if data_parts:")
	p(`        yield "\n".join(data_parts)`)
	p("")
	p("")
}
