# Code generated by protoc-gen-onekit-py-client. DO NOT EDIT.
# source: backward_compat.proto

from __future__ import annotations

import base64
import binascii
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any, AsyncIterator, Iterator, Mapping, Optional, Protocol, Sequence, Union

@dataclass
class HttpResponse:
    """Minimal HTTP response shape returned by every HttpTransport."""
    status: int
    headers: Mapping[str, str]
    body: bytes


class HttpTransport(Protocol):
    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse: ...


class UrllibTransport:
    """Default transport built on the Python standard library."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        req = urllib.request.Request(url=url, method=method, data=body)
        for key, value in headers.items():
            req.add_header(key, value)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return HttpResponse(
                    status=resp.status,
                    headers={k: v for k, v in resp.headers.items()},
                    body=resp.read(),
                )
        except urllib.error.HTTPError as exc:
            return HttpResponse(
                status=exc.code,
                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},
                body=exc.read() if hasattr(exc, "read") else b"",
            )


@dataclass
class FieldViolation:
    """Single validation violation, matching onekit.http.FieldViolation."""
    field: str
    description: str = ""


class ApiError(Exception):
    """Base exception for any non-2xx HTTP response."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        self.status = status
        self.body = body
        self.headers = headers or {}
        super().__init__(f"HTTP {status}")


class ValidationError(ApiError):
    """Raised on HTTP 400 when the server returns onekit.http.ValidationError JSON."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
        violations: Optional[Sequence[FieldViolation]] = None,
    ) -> None:
        super().__init__(status, body, headers)
        self.violations: list[FieldViolation] = list(violations or [])


_ERROR_CLASSES: list[tuple[type[ApiError], set[str]]] = [
]


@dataclass
class ActionRequest:
    """Generated from proto message test.httpgen.compat.ActionRequest."""
    name: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["name"] = self.name
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "ActionRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "name" in data and data["name"] is not None:
            kwargs["name"] = str(data["name"])
        return cls(**kwargs)

@dataclass
class ActionResponse:
    """Generated from proto message test.httpgen.compat.ActionResponse."""
    success: bool = False

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["success"] = self.success
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "ActionResponse":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "success" in data and data["success"] is not None:
            kwargs["success"] = bool(data["success"])
        return cls(**kwargs)

@dataclass
class AnotherRequest:
    """Generated from proto message test.httpgen.compat.AnotherRequest."""
    value: int = 0

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["value"] = self.value
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "AnotherRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "value" in data and data["value"] is not None:
            kwargs["value"] = int(data["value"])
        return cls(**kwargs)

@dataclass
class AnotherResponse:
    """Generated from proto message test.httpgen.compat.AnotherResponse."""
    result: int = 0

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["result"] = self.result
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "AnotherResponse":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "result" in data and data["result"] is not None:
            kwargs["result"] = int(data["result"])
        return cls(**kwargs)

@dataclass
class SimpleRequest:
    """Generated from proto message test.httpgen.compat.SimpleRequest."""
    input: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["input"] = self.input
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "SimpleRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "input" in data and data["input"] is not None:
            kwargs["input"] = str(data["input"])
        return cls(**kwargs)

@dataclass
class SimpleResponse:
    """Generated from proto message test.httpgen.compat.SimpleResponse."""
    output: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["output"] = self.output
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "SimpleResponse":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "output" in data and data["output"] is not None:
            kwargs["output"] = str(data["output"])
        return cls(**kwargs)

@dataclass
class NoAnnotationsServiceClientOptions:
    """Construct-time options for NoAnnotationsServiceClient."""
    transport: Optional[HttpTransport] = None
    default_headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: str = "application/json"
    # Total attempts including the first (1 = no retries). Transport errors and
    # HTTP 429/502/503/504 are retried with exponential backoff. SSE never retries.
    max_retry_attempts: int = 1
    # Delay in seconds before the first retry; doubles on each subsequent retry.
    retry_backoff: float = 0.25


@dataclass
class NoAnnotationsServiceCallOptions:
    """Per-call options for NoAnnotationsServiceClient methods."""
    headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: Optional[str] = None


class NoAnnotationsServiceClient:
    """Generated client for test.httpgen.compat.NoAnnotationsService."""
    def __init__(
        self,
        base_url: str,
        options: Optional[NoAnnotationsServiceClientOptions] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        opts = options or NoAnnotationsServiceClientOptions()
        self._transport: HttpTransport = opts.transport or UrllibTransport()
        self._default_headers: dict[str, str] = dict(opts.default_headers or {})
        self._timeout = opts.timeout
        self._content_type = opts.content_type
        self._max_retry_attempts = opts.max_retry_attempts
        self._retry_backoff = opts.retry_backoff

    def simple_action(
        self,
        req: SimpleRequest,
        options: Optional[NoAnnotationsServiceCallOptions] = None,
    ) -> SimpleResponse:
        """Calls test.httpgen.compat.NoAnnotationsService.SimpleAction."""
        opts = options or NoAnnotationsServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/simpleAction"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return SimpleResponse()
        return SimpleResponse.from_dict(json.loads(resp.body))

    def another_action(
        self,
        req: AnotherRequest,
        options: Optional[NoAnnotationsServiceCallOptions] = None,
    ) -> AnotherResponse:
        """Calls test.httpgen.compat.NoAnnotationsService.AnotherAction."""
        opts = options or NoAnnotationsServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/anotherAction"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return AnotherResponse()
        return AnotherResponse.from_dict(json.loads(resp.body))

    def _request_with_retries(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        """Executes a request, retrying transport errors and 429/502/503/504."""
        attempts = max(1, self._max_retry_attempts)
        last_exc: Optional[Exception] = None
        for attempt in range(attempts):
            if attempt > 0:
                time.sleep(self._retry_backoff * (2 ** (attempt - 1)))
            try:
                resp = self._transport.request(
                    method=method, url=url, headers=headers, body=body, timeout=timeout,
                )
            except Exception as exc:  # noqa: BLE001 - transport errors vary by implementation
                last_exc = exc
                continue
            if attempt < attempts - 1 and resp.status in (429, 502, 503, 504):
                continue
            return resp
        assert last_exc is not None
        raise last_exc

    def _raise_for_status(self, resp: HttpResponse) -> None:
        """Map a non-2xx response to the most specific exception available."""
        body = resp.body or b""
        parsed: Any = None
        ctype = (resp.headers or {}).get("Content-Type", "")
        looks_jsonish = "json" in ctype.lower() or body[:1] in (b"{", b"[")
        if looks_jsonish:
            try:
                parsed = json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                parsed = None
        if resp.status == 400 and isinstance(parsed, dict) and "violations" in parsed:
            violations = [
                FieldViolation(field=v.get("field", ""), description=v.get("description", ""))
                for v in parsed.get("violations", [])
            ]
            raise ValidationError(resp.status, body, resp.headers, violations)
        if isinstance(parsed, dict):
            for err_cls, required_keys in _ERROR_CLASSES:
                if required_keys and required_keys.issubset(parsed.keys()):
                    raise err_cls.populate(resp.status, body, resp.headers, parsed)
        raise ApiError(resp.status, body, resp.headers)

@dataclass
class BasePathOnlyServiceClientOptions:
    """Construct-time options for BasePathOnlyServiceClient."""
    transport: Optional[HttpTransport] = None
    default_headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: str = "application/json"
    # Total attempts including the first (1 = no retries). Transport errors and
    # HTTP 429/502/503/504 are retried with exponential backoff. SSE never retries.
    max_retry_attempts: int = 1
    # Delay in seconds before the first retry; doubles on each subsequent retry.
    retry_backoff: float = 0.25


@dataclass
class BasePathOnlyServiceCallOptions:
    """Per-call options for BasePathOnlyServiceClient methods."""
    headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: Optional[str] = None


class BasePathOnlyServiceClient:
    """Generated client for test.httpgen.compat.BasePathOnlyService."""
    def __init__(
        self,
        base_url: str,
        options: Optional[BasePathOnlyServiceClientOptions] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        opts = options or BasePathOnlyServiceClientOptions()
        self._transport: HttpTransport = opts.transport or UrllibTransport()
        self._default_headers: dict[str, str] = dict(opts.default_headers or {})
        self._timeout = opts.timeout
        self._content_type = opts.content_type
        self._max_retry_attempts = opts.max_retry_attempts
        self._retry_backoff = opts.retry_backoff

    def action_one(
        self,
        req: ActionRequest,
        options: Optional[BasePathOnlyServiceCallOptions] = None,
    ) -> ActionResponse:
        """Calls test.httpgen.compat.BasePathOnlyService.ActionOne."""
        opts = options or BasePathOnlyServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v2/actionOne"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return ActionResponse()
        return ActionResponse.from_dict(json.loads(resp.body))

    def action_two(
        self,
        req: ActionRequest,
        options: Optional[BasePathOnlyServiceCallOptions] = None,
    ) -> ActionResponse:
        """Calls test.httpgen.compat.BasePathOnlyService.ActionTwo."""
        opts = options or BasePathOnlyServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v2/actionTwo"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return ActionResponse()
        return ActionResponse.from_dict(json.loads(resp.body))

    def _request_with_retries(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        """Executes a request, retrying transport errors and 429/502/503/504."""
        attempts = max(1, self._max_retry_attempts)
        last_exc: Optional[Exception] = None
        for attempt in range(attempts):
            if attempt > 0:
                time.sleep(self._retry_backoff * (2 ** (attempt - 1)))
            try:
                resp = self._transport.request(
                    method=method, url=url, headers=headers, body=body, timeout=timeout,
                )
            except Exception as exc:  # noqa: BLE001 - transport errors vary by implementation
                last_exc = exc
                continue
            if attempt < attempts - 1 and resp.status in (429, 502, 503, 504):
                continue
            return resp
        assert last_exc is not None
        raise last_exc

    def _raise_for_status(self, resp: HttpResponse) -> None:
        """Map a non-2xx response to the most specific exception available."""
        body = resp.body or b""
        parsed: Any = None
        ctype = (resp.headers or {}).get("Content-Type", "")
        looks_jsonish = "json" in ctype.lower() or body[:1] in (b"{", b"[")
        if looks_jsonish:
            try:
                parsed = json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                parsed = None
        if resp.status == 400 and isinstance(parsed, dict) and "violations" in parsed:
            violations = [
                FieldViolation(field=v.get("field", ""), description=v.get("description", ""))
                for v in parsed.get("violations", [])
            ]
            raise ValidationError(resp.status, body, resp.headers, violations)
        if isinstance(parsed, dict):
            for err_cls, required_keys in _ERROR_CLASSES:
                if required_keys and required_keys.issubset(parsed.keys()):
                    raise err_cls.populate(resp.status, body, resp.headers, parsed)
        raise ApiError(resp.status, body, resp.headers)

