# Code generated by protoc-gen-onekit-py-client. DO NOT EDIT.
# source: complex_features.proto

from __future__ import annotations

import base64
import binascii
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any, AsyncIterator, Iterator, Mapping, Optional, Protocol, Sequence, Union

@dataclass
class HttpResponse:
    """Minimal HTTP response shape returned by every HttpTransport."""
    status: int
    headers: Mapping[str, str]
    body: bytes


class HttpTransport(Protocol):
    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse: ...


class UrllibTransport:
    """Default transport built on the Python standard library."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        req = urllib.request.Request(url=url, method=method, data=body)
        for key, value in headers.items():
            req.add_header(key, value)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return HttpResponse(
                    status=resp.status,
                    headers={k: v for k, v in resp.headers.items()},
                    body=resp.read(),
                )
        except urllib.error.HTTPError as exc:
            return HttpResponse(
                status=exc.code,
                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},
                body=exc.read() if hasattr(exc, "read") else b"",
            )


class Priority(IntEnum):
    """Generated from proto enum test.tsclientgen.Priority."""
    PRIORITY_UNSPECIFIED = 0
    PRIORITY_LOW = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_HIGH = 3
    PRIORITY_URGENT = 4


Priority_JSON_VALUES: Mapping[Priority, str] = {}

def _decode_enum_Priority(value: Any) -> Priority:
    if isinstance(value, int):
        return Priority(value)
    if isinstance(value, str):
        for member, json_value in Priority_JSON_VALUES.items():
            if json_value == value:
                return member
        try:
            return Priority[value]
        except KeyError:
            raise ValueError(f"unknown Priority value: {value!r}")
    raise TypeError(f"cannot decode Priority from {type(value).__name__}")


class Status(IntEnum):
    """Generated from proto enum test.tsclientgen.Status."""
    STATUS_UNSPECIFIED = 0
    STATUS_PENDING = 1
    STATUS_IN_PROGRESS = 2
    STATUS_DONE = 3
    STATUS_ARCHIVED = 4


Status_JSON_VALUES: Mapping[Status, str] = {}

def _decode_enum_Status(value: Any) -> Status:
    if isinstance(value, int):
        return Status(value)
    if isinstance(value, str):
        for member, json_value in Status_JSON_VALUES.items():
            if json_value == value:
                return member
        try:
            return Status[value]
        except KeyError:
            raise ValueError(f"unknown Status value: {value!r}")
    raise TypeError(f"cannot decode Status from {type(value).__name__}")


@dataclass
class FieldViolation:
    """Single validation violation, matching onekit.http.FieldViolation."""
    field: str
    description: str = ""


class ApiError(Exception):
    """Base exception for any non-2xx HTTP response."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        self.status = status
        self.body = body
        self.headers = headers or {}
        super().__init__(f"HTTP {status}")


class ValidationError(ApiError):
    """Raised on HTTP 400 when the server returns onekit.http.ValidationError JSON."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
        violations: Optional[Sequence[FieldViolation]] = None,
    ) -> None:
        super().__init__(status, body, headers)
        self.violations: list[FieldViolation] = list(violations or [])


_ERROR_CLASSES: list[tuple[type[ApiError], set[str]]] = [
]


@dataclass
class Address:
    """Generated from proto message test.tsclientgen.Address."""
    street: str = ""
    city: str = ""
    zip_code: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["street"] = self.street
        d["city"] = self.city
        d["zipCode"] = self.zip_code
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Address":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "street" in data and data["street"] is not None:
            kwargs["street"] = str(data["street"])
        if "city" in data and data["city"] is not None:
            kwargs["city"] = str(data["city"])
        if "zipCode" in data and data["zipCode"] is not None:
            kwargs["zip_code"] = str(data["zipCode"])
        return cls(**kwargs)

@dataclass
class Bar:
    """Generated from proto message test.tsclientgen.Bar."""
    symbol: str = ""
    price: float = 0.0
    volume: str = "0"

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["symbol"] = self.symbol
        d["price"] = self.price
        d["volume"] = str(self.volume)
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Bar":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "symbol" in data and data["symbol"] is not None:
            kwargs["symbol"] = str(data["symbol"])
        if "price" in data and data["price"] is not None:
            kwargs["price"] = float(data["price"])
        if "volume" in data and data["volume"] is not None:
            kwargs["volume"] = str(data["volume"])
        return cls(**kwargs)

@dataclass
class BarWrapper:
    """Generated from proto message test.tsclientgen.BarWrapper."""
    bars: list[Bar] = field(default_factory=list)

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready value (root-unwrapped)."""
        return [v.to_dict() for v in self.bars]

    @classmethod
    def from_dict(cls, data: Any) -> "BarWrapper":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        return cls(bars=[Bar.from_dict(v) for v in data])

@dataclass
class BarsBySymbol:
    """Generated from proto message test.tsclientgen.BarsBySymbol."""
    data: dict[str, BarWrapper] = field(default_factory=dict)

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        if self.data:
            d["data"] = {k: [x.to_dict() for x in v.bars] for k, v in self.data.items()}
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "BarsBySymbol":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "data" in data and data["data"] is not None:
            kwargs["data"] = {
                k: BarWrapper(bars=[Bar.from_dict(x) for x in v])
                for k, v in data["data"].items()
            }
        return cls(**kwargs)

@dataclass
class CombinedUnwrap:
    """Generated from proto message test.tsclientgen.CombinedUnwrap."""
    data: dict[str, BarWrapper] = field(default_factory=dict)

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready value (root-unwrapped)."""
        return {k: v.to_dict() for k, v in self.data.items()}

    @classmethod
    def from_dict(cls, data: Any) -> "CombinedUnwrap":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        return cls(data={k: BarWrapper.from_dict(v) for k, v in data.items()})

@dataclass
class CreateNoteRequest:
    """Generated from proto message test.tsclientgen.CreateNoteRequest."""
    title: str = ""
    content: str = ""
    priority: Priority = Priority.PRIORITY_UNSPECIFIED
    status: Status = Status.STATUS_UNSPECIFIED
    tags: list[Tag] = field(default_factory=list)
    metadata: dict[str, str] = field(default_factory=dict)
    due_date: Optional[str] = None
    address: Optional[Address] = None

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["title"] = self.title
        d["content"] = self.content
        d["priority"] = Priority_JSON_VALUES.get(self.priority, self.priority.name)
        d["status"] = Status_JSON_VALUES.get(self.status, self.status.name)
        if self.tags:
            d["tags"] = [v.to_dict() for v in self.tags]
        if self.metadata:
            d["metadata"] = {k: v for k, v in self.metadata.items()}
        if self.due_date is not None:
            d["dueDate"] = self.due_date
        if self.address is not None:
            d["address"] = self.address.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "CreateNoteRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "title" in data and data["title"] is not None:
            kwargs["title"] = str(data["title"])
        if "content" in data and data["content"] is not None:
            kwargs["content"] = str(data["content"])
        if "priority" in data and data["priority"] is not None:
            kwargs["priority"] = _decode_enum_Priority(data["priority"])
        if "status" in data and data["status"] is not None:
            kwargs["status"] = _decode_enum_Status(data["status"])
        if "tags" in data and data["tags"] is not None:
            kwargs["tags"] = [Tag.from_dict(v) for v in data["tags"]]
        if "metadata" in data and data["metadata"] is not None:
            kwargs["metadata"] = {k: str(v) for k, v in data["metadata"].items()}
        if "dueDate" in data and data["dueDate"] is not None:
            kwargs["due_date"] = str(data["dueDate"])
        if "address" in data and data["address"] is not None:
            kwargs["address"] = Address.from_dict(data["address"])
        return cls(**kwargs)

@dataclass
class GetBarsBySymbolRequest:
    """Generated from proto message test.tsclientgen.GetBarsBySymbolRequest."""
    symbols: list[str] = field(default_factory=list)

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        if self.symbols:
            d["symbols"] = [v for v in self.symbols]
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetBarsBySymbolRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "symbols" in data and data["symbols"] is not None:
            kwargs["symbols"] = [str(v) for v in data["symbols"]]
        return cls(**kwargs)

@dataclass
class GetCombinedUnwrapRequest:
    """Generated from proto message test.tsclientgen.GetCombinedUnwrapRequest."""
    market: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["market"] = self.market
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetCombinedUnwrapRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "market" in data and data["market"] is not None:
            kwargs["market"] = str(data["market"])
        return cls(**kwargs)

@dataclass
class GetNoteListRequest:
    """Generated from proto message test.tsclientgen.GetNoteListRequest."""
    category: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["category"] = self.category
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetNoteListRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "category" in data and data["category"] is not None:
            kwargs["category"] = str(data["category"])
        return cls(**kwargs)

@dataclass
class GetNoteMapRequest:
    """Generated from proto message test.tsclientgen.GetNoteMapRequest."""
    owner_id: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["ownerId"] = self.owner_id
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetNoteMapRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "ownerId" in data and data["ownerId"] is not None:
            kwargs["owner_id"] = str(data["ownerId"])
        return cls(**kwargs)

@dataclass
class GetNoteRequest:
    """Generated from proto message test.tsclientgen.GetNoteRequest."""
    note_id: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["noteId"] = self.note_id
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetNoteRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "noteId" in data and data["noteId"] is not None:
            kwargs["note_id"] = str(data["noteId"])
        return cls(**kwargs)

@dataclass
class ListNotesRequest:
    """Generated from proto message test.tsclientgen.ListNotesRequest."""
    page: int = 0
    page_size: int = 0
    filter: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["page"] = self.page
        d["pageSize"] = self.page_size
        d["filter"] = self.filter
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "ListNotesRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "page" in data and data["page"] is not None:
            kwargs["page"] = int(data["page"])
        if "pageSize" in data and data["pageSize"] is not None:
            kwargs["page_size"] = int(data["pageSize"])
        if "filter" in data and data["filter"] is not None:
            kwargs["filter"] = str(data["filter"])
        return cls(**kwargs)

@dataclass
class ListNotesResponse:
    """Generated from proto message test.tsclientgen.ListNotesResponse."""
    notes: list[Note] = field(default_factory=list)
    total_count: int = 0

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        if self.notes:
            d["notes"] = [v.to_dict() for v in self.notes]
        d["totalCount"] = self.total_count
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "ListNotesResponse":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "notes" in data and data["notes"] is not None:
            kwargs["notes"] = [Note.from_dict(v) for v in data["notes"]]
        if "totalCount" in data and data["totalCount"] is not None:
            kwargs["total_count"] = int(data["totalCount"])
        return cls(**kwargs)

@dataclass
class Note:
    """Generated from proto message test.tsclientgen.Note."""
    id: str = ""
    title: str = ""
    content: str = ""
    priority: Priority = Priority.PRIORITY_UNSPECIFIED
    status: Status = Status.STATUS_UNSPECIFIED
    tags: list[Tag] = field(default_factory=list)
    metadata: dict[str, str] = field(default_factory=dict)
    due_date: Optional[str] = None
    address: Optional[Address] = None

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        d["title"] = self.title
        d["content"] = self.content
        d["priority"] = Priority_JSON_VALUES.get(self.priority, self.priority.name)
        d["status"] = Status_JSON_VALUES.get(self.status, self.status.name)
        if self.tags:
            d["tags"] = [v.to_dict() for v in self.tags]
        if self.metadata:
            d["metadata"] = {k: v for k, v in self.metadata.items()}
        if self.due_date is not None:
            d["dueDate"] = self.due_date
        if self.address is not None:
            d["address"] = self.address.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Note":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        if "title" in data and data["title"] is not None:
            kwargs["title"] = str(data["title"])
        if "content" in data and data["content"] is not None:
            kwargs["content"] = str(data["content"])
        if "priority" in data and data["priority"] is not None:
            kwargs["priority"] = _decode_enum_Priority(data["priority"])
        if "status" in data and data["status"] is not None:
            kwargs["status"] = _decode_enum_Status(data["status"])
        if "tags" in data and data["tags"] is not None:
            kwargs["tags"] = [Tag.from_dict(v) for v in data["tags"]]
        if "metadata" in data and data["metadata"] is not None:
            kwargs["metadata"] = {k: str(v) for k, v in data["metadata"].items()}
        if "dueDate" in data and data["dueDate"] is not None:
            kwargs["due_date"] = str(data["dueDate"])
        if "address" in data and data["address"] is not None:
            kwargs["address"] = Address.from_dict(data["address"])
        return cls(**kwargs)

@dataclass
class NoteList:
    """Generated from proto message test.tsclientgen.NoteList."""
    notes: list[Note] = field(default_factory=list)

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready value (root-unwrapped)."""
        return [v.to_dict() for v in self.notes]

    @classmethod
    def from_dict(cls, data: Any) -> "NoteList":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        return cls(notes=[Note.from_dict(v) for v in data])

@dataclass
class NoteMap:
    """Generated from proto message test.tsclientgen.NoteMap."""
    notes: dict[str, Note] = field(default_factory=dict)

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready value (root-unwrapped)."""
        return {k: v.to_dict() for k, v in self.notes.items()}

    @classmethod
    def from_dict(cls, data: Any) -> "NoteMap":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        return cls(notes={k: Note.from_dict(v) for k, v in data.items()})

@dataclass
class Tag:
    """Generated from proto message test.tsclientgen.Tag."""
    name: str = ""
    color: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["name"] = self.name
        d["color"] = self.color
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Tag":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "name" in data and data["name"] is not None:
            kwargs["name"] = str(data["name"])
        if "color" in data and data["color"] is not None:
            kwargs["color"] = str(data["color"])
        return cls(**kwargs)

@dataclass
class UpdateNoteRequest:
    """Generated from proto message test.tsclientgen.UpdateNoteRequest."""
    note_id: str = ""
    title: str = ""
    content: str = ""
    priority: Priority = Priority.PRIORITY_UNSPECIFIED

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["noteId"] = self.note_id
        d["title"] = self.title
        d["content"] = self.content
        d["priority"] = Priority_JSON_VALUES.get(self.priority, self.priority.name)
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "UpdateNoteRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "noteId" in data and data["noteId"] is not None:
            kwargs["note_id"] = str(data["noteId"])
        if "title" in data and data["title"] is not None:
            kwargs["title"] = str(data["title"])
        if "content" in data and data["content"] is not None:
            kwargs["content"] = str(data["content"])
        if "priority" in data and data["priority"] is not None:
            kwargs["priority"] = _decode_enum_Priority(data["priority"])
        return cls(**kwargs)

@dataclass
class FeatureServiceClientOptions:
    """Construct-time options for FeatureServiceClient."""
    transport: Optional[HttpTransport] = None
    default_headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: str = "application/json"
    # Total attempts including the first (1 = no retries). Transport errors and
    # HTTP 429/502/503/504 are retried with exponential backoff. SSE never retries.
    max_retry_attempts: int = 1
    # Delay in seconds before the first retry; doubles on each subsequent retry.
    retry_backoff: float = 0.25
    api_key: Optional[str] = None
    tenant_id: Optional[str] = None


@dataclass
class FeatureServiceCallOptions:
    """Per-call options for FeatureServiceClient methods."""
    headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: Optional[str] = None
    api_key: Optional[str] = None
    tenant_id: Optional[str] = None
    request_id: Optional[str] = None
    idempotency_key: Optional[str] = None


class FeatureServiceClient:
    """Generated client for test.tsclientgen.FeatureService."""
    def __init__(
        self,
        base_url: str,
        options: Optional[FeatureServiceClientOptions] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        opts = options or FeatureServiceClientOptions()
        self._transport: HttpTransport = opts.transport or UrllibTransport()
        self._default_headers: dict[str, str] = dict(opts.default_headers or {})
        self._timeout = opts.timeout
        self._content_type = opts.content_type
        self._max_retry_attempts = opts.max_retry_attempts
        self._retry_backoff = opts.retry_backoff
        if opts.api_key is not None:
            self._default_headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            self._default_headers["X-Tenant-ID"] = opts.tenant_id

    def list_notes(
        self,
        req: ListNotesRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> ListNotesResponse:
        """Calls test.tsclientgen.FeatureService.ListNotes."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/notes"
        query_pairs: list[tuple[str, str]] = []
        if req.page is not None and req.page != 0:
            query_pairs.append(("page", str(req.page)))
        if req.page_size is not None and req.page_size != 0:
            query_pairs.append(("page_size", str(req.page_size)))
        if req.filter:
            query_pairs.append(("filter", str(req.filter)))
        if query_pairs:
            path = path + "?" + urllib.parse.urlencode(query_pairs, doseq=True)
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        body: Optional[bytes] = None
        resp = self._request_with_retries(
            method="GET",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return ListNotesResponse()
        return ListNotesResponse.from_dict(json.loads(resp.body))

    def get_note(
        self,
        req: GetNoteRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> Note:
        """Calls test.tsclientgen.FeatureService.GetNote."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/notes/{note_id}"
        path = path.replace("{note_id}", urllib.parse.quote(str(req.note_id), safe=""))
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        body: Optional[bytes] = None
        resp = self._request_with_retries(
            method="GET",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return Note()
        return Note.from_dict(json.loads(resp.body))

    def create_note(
        self,
        req: CreateNoteRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> Note:
        """Calls test.tsclientgen.FeatureService.CreateNote."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/notes"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        if opts.request_id is not None:
            headers["X-Request-ID"] = opts.request_id
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return Note()
        return Note.from_dict(json.loads(resp.body))

    def update_note(
        self,
        req: UpdateNoteRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> Note:
        """Calls test.tsclientgen.FeatureService.UpdateNote."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/notes/{note_id}"
        path = path.replace("{note_id}", urllib.parse.quote(str(req.note_id), safe=""))
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        if opts.idempotency_key is not None:
            headers["X-Idempotency-Key"] = opts.idempotency_key
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="PUT",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return Note()
        return Note.from_dict(json.loads(resp.body))

    def get_note_list(
        self,
        req: GetNoteListRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> NoteList:
        """Calls test.tsclientgen.FeatureService.GetNoteList."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/notes/list"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return NoteList()
        return NoteList.from_dict(json.loads(resp.body))

    def get_note_map(
        self,
        req: GetNoteMapRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> NoteMap:
        """Calls test.tsclientgen.FeatureService.GetNoteMap."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/notes/map"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return NoteMap()
        return NoteMap.from_dict(json.loads(resp.body))

    def get_bars_by_symbol(
        self,
        req: GetBarsBySymbolRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> BarsBySymbol:
        """Calls test.tsclientgen.FeatureService.GetBarsBySymbol."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/bars"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return BarsBySymbol()
        return BarsBySymbol.from_dict(json.loads(resp.body))

    def get_combined_unwrap(
        self,
        req: GetCombinedUnwrapRequest,
        options: Optional[FeatureServiceCallOptions] = None,
    ) -> CombinedUnwrap:
        """Calls test.tsclientgen.FeatureService.GetCombinedUnwrap."""
        opts = options or FeatureServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/bars/combined"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        if opts.api_key is not None:
            headers["X-API-Key"] = opts.api_key
        if opts.tenant_id is not None:
            headers["X-Tenant-ID"] = opts.tenant_id
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return CombinedUnwrap()
        return CombinedUnwrap.from_dict(json.loads(resp.body))

    def _request_with_retries(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        """Executes a request, retrying transport errors and 429/502/503/504."""
        attempts = max(1, self._max_retry_attempts)
        last_exc: Optional[Exception] = None
        for attempt in range(attempts):
            if attempt > 0:
                time.sleep(self._retry_backoff * (2 ** (attempt - 1)))
            try:
                resp = self._transport.request(
                    method=method, url=url, headers=headers, body=body, timeout=timeout,
                )
            except Exception as exc:  # noqa: BLE001 - transport errors vary by implementation
                last_exc = exc
                continue
            if attempt < attempts - 1 and resp.status in (429, 502, 503, 504):
                continue
            return resp
        assert last_exc is not None
        raise last_exc

    def _raise_for_status(self, resp: HttpResponse) -> None:
        """Map a non-2xx response to the most specific exception available."""
        body = resp.body or b""
        parsed: Any = None
        ctype = (resp.headers or {}).get("Content-Type", "")
        looks_jsonish = "json" in ctype.lower() or body[:1] in (b"{", b"[")
        if looks_jsonish:
            try:
                parsed = json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                parsed = None
        if resp.status == 400 and isinstance(parsed, dict) and "violations" in parsed:
            violations = [
                FieldViolation(field=v.get("field", ""), description=v.get("description", ""))
                for v in parsed.get("violations", [])
            ]
            raise ValidationError(resp.status, body, resp.headers, violations)
        if isinstance(parsed, dict):
            for err_cls, required_keys in _ERROR_CLASSES:
                if required_keys and required_keys.issubset(parsed.keys()):
                    raise err_cls.populate(resp.status, body, resp.headers, parsed)
        raise ApiError(resp.status, body, resp.headers)

