# Code generated by protoc-gen-onekit-py-client. DO NOT EDIT.
# source: empty_behavior.proto

from __future__ import annotations

import base64
import binascii
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any, AsyncIterator, Iterator, Mapping, Optional, Protocol, Sequence, Union

@dataclass
class HttpResponse:
    """Minimal HTTP response shape returned by every HttpTransport."""
    status: int
    headers: Mapping[str, str]
    body: bytes


class HttpTransport(Protocol):
    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse: ...


class UrllibTransport:
    """Default transport built on the Python standard library."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        req = urllib.request.Request(url=url, method=method, data=body)
        for key, value in headers.items():
            req.add_header(key, value)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return HttpResponse(
                    status=resp.status,
                    headers={k: v for k, v in resp.headers.items()},
                    body=resp.read(),
                )
        except urllib.error.HTTPError as exc:
            return HttpResponse(
                status=exc.code,
                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},
                body=exc.read() if hasattr(exc, "read") else b"",
            )


@dataclass
class FieldViolation:
    """Single validation violation, matching onekit.http.FieldViolation."""
    field: str
    description: str = ""


class ApiError(Exception):
    """Base exception for any non-2xx HTTP response."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        self.status = status
        self.body = body
        self.headers = headers or {}
        super().__init__(f"HTTP {status}")


class ValidationError(ApiError):
    """Raised on HTTP 400 when the server returns onekit.http.ValidationError JSON."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
        violations: Optional[Sequence[FieldViolation]] = None,
    ) -> None:
        super().__init__(status, body, headers)
        self.violations: list[FieldViolation] = list(violations or [])


_ERROR_CLASSES: list[tuple[type[ApiError], set[str]]] = [
]


@dataclass
class GetResponseRequest:
    """Generated from proto message testdata.empty_behavior.GetResponseRequest."""
    id: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetResponseRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        return cls(**kwargs)

@dataclass
class Metadata:
    """Generated from proto message testdata.empty_behavior.Metadata."""
    key: str = ""
    value: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["key"] = self.key
        d["value"] = self.value
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Metadata":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "key" in data and data["key"] is not None:
            kwargs["key"] = str(data["key"])
        if "value" in data and data["value"] is not None:
            kwargs["value"] = str(data["value"])
        return cls(**kwargs)

@dataclass
class Response:
    """Generated from proto message testdata.empty_behavior.Response."""
    id: str = ""
    metadata_preserve: Optional[Metadata] = None
    metadata_null: Optional[Metadata] = None
    metadata_omit: Optional[Metadata] = None
    metadata_default: Optional[Metadata] = None
    settings: Optional[Settings] = None

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        if self.metadata_preserve is not None:
            d["metadataPreserve"] = self.metadata_preserve.to_dict()
        if self.metadata_null is None:
            d["metadataNull"] = None
        else:
            d["metadataNull"] = self.metadata_null.to_dict()
        if self.metadata_omit is not None:
            _v = self.metadata_omit.to_dict()
            if _v:
                d["metadataOmit"] = _v
        if self.metadata_default is not None:
            d["metadataDefault"] = self.metadata_default.to_dict()
        if self.settings is None:
            d["settings"] = None
        else:
            d["settings"] = self.settings.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Response":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        if "metadataPreserve" in data and data["metadataPreserve"] is not None:
            kwargs["metadata_preserve"] = Metadata.from_dict(data["metadataPreserve"])
        if "metadataNull" in data and data["metadataNull"] is not None:
            kwargs["metadata_null"] = Metadata.from_dict(data["metadataNull"])
        if "metadataOmit" in data and data["metadataOmit"] is not None:
            kwargs["metadata_omit"] = Metadata.from_dict(data["metadataOmit"])
        if "metadataDefault" in data and data["metadataDefault"] is not None:
            kwargs["metadata_default"] = Metadata.from_dict(data["metadataDefault"])
        if "settings" in data and data["settings"] is not None:
            kwargs["settings"] = Settings.from_dict(data["settings"])
        return cls(**kwargs)

@dataclass
class Settings:
    """Generated from proto message testdata.empty_behavior.Settings."""
    enabled: bool = False
    timeout: int = 0

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["enabled"] = self.enabled
        d["timeout"] = self.timeout
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Settings":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "enabled" in data and data["enabled"] is not None:
            kwargs["enabled"] = bool(data["enabled"])
        if "timeout" in data and data["timeout"] is not None:
            kwargs["timeout"] = int(data["timeout"])
        return cls(**kwargs)

@dataclass
class EmptyBehaviorServiceClientOptions:
    """Construct-time options for EmptyBehaviorServiceClient."""
    transport: Optional[HttpTransport] = None
    default_headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: str = "application/json"
    # Total attempts including the first (1 = no retries). Transport errors and
    # HTTP 429/502/503/504 are retried with exponential backoff. SSE never retries.
    max_retry_attempts: int = 1
    # Delay in seconds before the first retry; doubles on each subsequent retry.
    retry_backoff: float = 0.25


@dataclass
class EmptyBehaviorServiceCallOptions:
    """Per-call options for EmptyBehaviorServiceClient methods."""
    headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: Optional[str] = None


class EmptyBehaviorServiceClient:
    """Generated client for testdata.empty_behavior.EmptyBehaviorService."""
    def __init__(
        self,
        base_url: str,
        options: Optional[EmptyBehaviorServiceClientOptions] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        opts = options or EmptyBehaviorServiceClientOptions()
        self._transport: HttpTransport = opts.transport or UrllibTransport()
        self._default_headers: dict[str, str] = dict(opts.default_headers or {})
        self._timeout = opts.timeout
        self._content_type = opts.content_type
        self._max_retry_attempts = opts.max_retry_attempts
        self._retry_backoff = opts.retry_backoff

    def get_response(
        self,
        req: GetResponseRequest,
        options: Optional[EmptyBehaviorServiceCallOptions] = None,
    ) -> Response:
        """Calls testdata.empty_behavior.EmptyBehaviorService.GetResponse."""
        opts = options or EmptyBehaviorServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/responses/{id}"
        path = path.replace("{id}", urllib.parse.quote(str(req.id), safe=""))
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body: Optional[bytes] = None
        resp = self._request_with_retries(
            method="GET",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return Response()
        return Response.from_dict(json.loads(resp.body))

    def _request_with_retries(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        """Executes a request, retrying transport errors and 429/502/503/504."""
        attempts = max(1, self._max_retry_attempts)
        last_exc: Optional[Exception] = None
        for attempt in range(attempts):
            if attempt > 0:
                time.sleep(self._retry_backoff * (2 ** (attempt - 1)))
            try:
                resp = self._transport.request(
                    method=method, url=url, headers=headers, body=body, timeout=timeout,
                )
            except Exception as exc:  # noqa: BLE001 - transport errors vary by implementation
                last_exc = exc
                continue
            if attempt < attempts - 1 and resp.status in (429, 502, 503, 504):
                continue
            return resp
        assert last_exc is not None
        raise last_exc

    def _raise_for_status(self, resp: HttpResponse) -> None:
        """Map a non-2xx response to the most specific exception available."""
        body = resp.body or b""
        parsed: Any = None
        ctype = (resp.headers or {}).get("Content-Type", "")
        looks_jsonish = "json" in ctype.lower() or body[:1] in (b"{", b"[")
        if looks_jsonish:
            try:
                parsed = json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                parsed = None
        if resp.status == 400 and isinstance(parsed, dict) and "violations" in parsed:
            violations = [
                FieldViolation(field=v.get("field", ""), description=v.get("description", ""))
                for v in parsed.get("violations", [])
            ]
            raise ValidationError(resp.status, body, resp.headers, violations)
        if isinstance(parsed, dict):
            for err_cls, required_keys in _ERROR_CLASSES:
                if required_keys and required_keys.issubset(parsed.keys()):
                    raise err_cls.populate(resp.status, body, resp.headers, parsed)
        raise ApiError(resp.status, body, resp.headers)

