# Code generated by protoc-gen-onekit-py-client. DO NOT EDIT.
# source: flatten.proto

from __future__ import annotations

import base64
import binascii
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any, AsyncIterator, Iterator, Mapping, Optional, Protocol, Sequence, Union

@dataclass
class HttpResponse:
    """Minimal HTTP response shape returned by every HttpTransport."""
    status: int
    headers: Mapping[str, str]
    body: bytes


class HttpTransport(Protocol):
    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse: ...


class UrllibTransport:
    """Default transport built on the Python standard library."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        req = urllib.request.Request(url=url, method=method, data=body)
        for key, value in headers.items():
            req.add_header(key, value)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return HttpResponse(
                    status=resp.status,
                    headers={k: v for k, v in resp.headers.items()},
                    body=resp.read(),
                )
        except urllib.error.HTTPError as exc:
            return HttpResponse(
                status=exc.code,
                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},
                body=exc.read() if hasattr(exc, "read") else b"",
            )


@dataclass
class FieldViolation:
    """Single validation violation, matching onekit.http.FieldViolation."""
    field: str
    description: str = ""


class ApiError(Exception):
    """Base exception for any non-2xx HTTP response."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        self.status = status
        self.body = body
        self.headers = headers or {}
        super().__init__(f"HTTP {status}")


class ValidationError(ApiError):
    """Raised on HTTP 400 when the server returns onekit.http.ValidationError JSON."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
        violations: Optional[Sequence[FieldViolation]] = None,
    ) -> None:
        super().__init__(status, body, headers)
        self.violations: list[FieldViolation] = list(violations or [])


_ERROR_CLASSES: list[tuple[type[ApiError], set[str]]] = [
]


@dataclass
class Address:
    """Generated from proto message testdata.flatten.Address."""
    street: str = ""
    city: str = ""
    zip: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["street"] = self.street
        d["city"] = self.city
        d["zip"] = self.zip
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Address":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "street" in data and data["street"] is not None:
            kwargs["street"] = str(data["street"])
        if "city" in data and data["city"] is not None:
            kwargs["city"] = str(data["city"])
        if "zip" in data and data["zip"] is not None:
            kwargs["zip"] = str(data["zip"])
        return cls(**kwargs)

@dataclass
class ContactInfo:
    """Generated from proto message testdata.flatten.ContactInfo."""
    email: str = ""
    phone: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["email"] = self.email
        d["phone"] = self.phone
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "ContactInfo":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "email" in data and data["email"] is not None:
            kwargs["email"] = str(data["email"])
        if "phone" in data and data["phone"] is not None:
            kwargs["phone"] = str(data["phone"])
        return cls(**kwargs)

@dataclass
class DualFlatten:
    """Generated from proto message testdata.flatten.DualFlatten."""
    id: str = ""
    billing: Optional[Address] = None
    shipping: Optional[Address] = None

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        if self.billing is not None:
            d["billing_street"] = self.billing.street
            d["billing_city"] = self.billing.city
            d["billing_zip"] = self.billing.zip
        if self.shipping is not None:
            d["shipping_street"] = self.shipping.street
            d["shipping_city"] = self.shipping.city
            d["shipping_zip"] = self.shipping.zip
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "DualFlatten":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        _sub_billing_kwargs: dict[str, Any] = {}
        if "billing_street" in data and data["billing_street"] is not None:
            _sub_billing_kwargs["street"] = str(data["billing_street"])
        if "billing_city" in data and data["billing_city"] is not None:
            _sub_billing_kwargs["city"] = str(data["billing_city"])
        if "billing_zip" in data and data["billing_zip"] is not None:
            _sub_billing_kwargs["zip"] = str(data["billing_zip"])
        if _sub_billing_kwargs:
            kwargs["billing"] = Address(**_sub_billing_kwargs)
        _sub_shipping_kwargs: dict[str, Any] = {}
        if "shipping_street" in data and data["shipping_street"] is not None:
            _sub_shipping_kwargs["street"] = str(data["shipping_street"])
        if "shipping_city" in data and data["shipping_city"] is not None:
            _sub_shipping_kwargs["city"] = str(data["shipping_city"])
        if "shipping_zip" in data and data["shipping_zip"] is not None:
            _sub_shipping_kwargs["zip"] = str(data["shipping_zip"])
        if _sub_shipping_kwargs:
            kwargs["shipping"] = Address(**_sub_shipping_kwargs)
        return cls(**kwargs)

@dataclass
class MixedFlatten:
    """Generated from proto message testdata.flatten.MixedFlatten."""
    id: str = ""
    address: Optional[Address] = None
    contact: Optional[ContactInfo] = None
    notes: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        if self.address is not None:
            d["street"] = self.address.street
            d["city"] = self.address.city
            d["zip"] = self.address.zip
        if self.contact is not None:
            d["contact"] = self.contact.to_dict()
        d["notes"] = self.notes
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "MixedFlatten":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        _sub_address_kwargs: dict[str, Any] = {}
        if "street" in data and data["street"] is not None:
            _sub_address_kwargs["street"] = str(data["street"])
        if "city" in data and data["city"] is not None:
            _sub_address_kwargs["city"] = str(data["city"])
        if "zip" in data and data["zip"] is not None:
            _sub_address_kwargs["zip"] = str(data["zip"])
        if _sub_address_kwargs:
            kwargs["address"] = Address(**_sub_address_kwargs)
        if "contact" in data and data["contact"] is not None:
            kwargs["contact"] = ContactInfo.from_dict(data["contact"])
        if "notes" in data and data["notes"] is not None:
            kwargs["notes"] = str(data["notes"])
        return cls(**kwargs)

@dataclass
class PlainNested:
    """Generated from proto message testdata.flatten.PlainNested."""
    id: str = ""
    address: Optional[Address] = None

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        if self.address is not None:
            d["address"] = self.address.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "PlainNested":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        if "address" in data and data["address"] is not None:
            kwargs["address"] = Address.from_dict(data["address"])
        return cls(**kwargs)

@dataclass
class SimpleFlatten:
    """Generated from proto message testdata.flatten.SimpleFlatten."""
    id: str = ""
    address: Optional[Address] = None

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting onekit JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        if self.address is not None:
            d["street"] = self.address.street
            d["city"] = self.address.city
            d["zip"] = self.address.zip
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "SimpleFlatten":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        _sub_address_kwargs: dict[str, Any] = {}
        if "street" in data and data["street"] is not None:
            _sub_address_kwargs["street"] = str(data["street"])
        if "city" in data and data["city"] is not None:
            _sub_address_kwargs["city"] = str(data["city"])
        if "zip" in data and data["zip"] is not None:
            _sub_address_kwargs["zip"] = str(data["zip"])
        if _sub_address_kwargs:
            kwargs["address"] = Address(**_sub_address_kwargs)
        return cls(**kwargs)

@dataclass
class FlattenServiceClientOptions:
    """Construct-time options for FlattenServiceClient."""
    transport: Optional[HttpTransport] = None
    default_headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: str = "application/json"
    # Total attempts including the first (1 = no retries). Transport errors and
    # HTTP 429/502/503/504 are retried with exponential backoff. SSE never retries.
    max_retry_attempts: int = 1
    # Delay in seconds before the first retry; doubles on each subsequent retry.
    retry_backoff: float = 0.25


@dataclass
class FlattenServiceCallOptions:
    """Per-call options for FlattenServiceClient methods."""
    headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: Optional[str] = None


class FlattenServiceClient:
    """Generated client for testdata.flatten.FlattenService."""
    def __init__(
        self,
        base_url: str,
        options: Optional[FlattenServiceClientOptions] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        opts = options or FlattenServiceClientOptions()
        self._transport: HttpTransport = opts.transport or UrllibTransport()
        self._default_headers: dict[str, str] = dict(opts.default_headers or {})
        self._timeout = opts.timeout
        self._content_type = opts.content_type
        self._max_retry_attempts = opts.max_retry_attempts
        self._retry_backoff = opts.retry_backoff

    def test_simple_flatten(
        self,
        req: SimpleFlatten,
        options: Optional[FlattenServiceCallOptions] = None,
    ) -> SimpleFlatten:
        """Calls testdata.flatten.FlattenService.TestSimpleFlatten."""
        opts = options or FlattenServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/flatten/simple"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return SimpleFlatten()
        return SimpleFlatten.from_dict(json.loads(resp.body))

    def test_dual_flatten(
        self,
        req: DualFlatten,
        options: Optional[FlattenServiceCallOptions] = None,
    ) -> DualFlatten:
        """Calls testdata.flatten.FlattenService.TestDualFlatten."""
        opts = options or FlattenServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/flatten/dual"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return DualFlatten()
        return DualFlatten.from_dict(json.loads(resp.body))

    def test_mixed_flatten(
        self,
        req: MixedFlatten,
        options: Optional[FlattenServiceCallOptions] = None,
    ) -> MixedFlatten:
        """Calls testdata.flatten.FlattenService.TestMixedFlatten."""
        opts = options or FlattenServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/flatten/mixed"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return MixedFlatten()
        return MixedFlatten.from_dict(json.loads(resp.body))

    def test_plain_nested(
        self,
        req: PlainNested,
        options: Optional[FlattenServiceCallOptions] = None,
    ) -> PlainNested:
        """Calls testdata.flatten.FlattenService.TestPlainNested."""
        opts = options or FlattenServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented")
        path = "/api/v1/flatten/plain"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body = json.dumps(req.to_dict()).encode("utf-8")
        resp = self._request_with_retries(
            method="POST",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return PlainNested()
        return PlainNested.from_dict(json.loads(resp.body))

    def _request_with_retries(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        """Executes a request, retrying transport errors and 429/502/503/504."""
        attempts = max(1, self._max_retry_attempts)
        last_exc: Optional[Exception] = None
        for attempt in range(attempts):
            if attempt > 0:
                time.sleep(self._retry_backoff * (2 ** (attempt - 1)))
            try:
                resp = self._transport.request(
                    method=method, url=url, headers=headers, body=body, timeout=timeout,
                )
            except Exception as exc:  # noqa: BLE001 - transport errors vary by implementation
                last_exc = exc
                continue
            if attempt < attempts - 1 and resp.status in (429, 502, 503, 504):
                continue
            return resp
        assert last_exc is not None
        raise last_exc

    def _raise_for_status(self, resp: HttpResponse) -> None:
        """Map a non-2xx response to the most specific exception available."""
        body = resp.body or b""
        parsed: Any = None
        ctype = (resp.headers or {}).get("Content-Type", "")
        looks_jsonish = "json" in ctype.lower() or body[:1] in (b"{", b"[")
        if looks_jsonish:
            try:
                parsed = json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                parsed = None
        if resp.status == 400 and isinstance(parsed, dict) and "violations" in parsed:
            violations = [
                FieldViolation(field=v.get("field", ""), description=v.get("description", ""))
                for v in parsed.get("violations", [])
            ]
            raise ValidationError(resp.status, body, resp.headers, violations)
        if isinstance(parsed, dict):
            for err_cls, required_keys in _ERROR_CLASSES:
                if required_keys and required_keys.issubset(parsed.keys()):
                    raise err_cls.populate(resp.status, body, resp.headers, parsed)
        raise ApiError(resp.status, body, resp.headers)

