// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: backward_compat.proto

package generated

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// NoAnnotationsServiceServer is the server API for NoAnnotationsService service.
type NoAnnotationsServiceServer interface {
	SimpleAction(context.Context, *SimpleRequest) (*SimpleResponse, error)
	AnotherAction(context.Context, *AnotherRequest) (*AnotherResponse, error)
}

// RegisterNoAnnotationsServiceServer registers the HTTP handlers for service NoAnnotationsService to the given mux.
func RegisterNoAnnotationsServiceServer(server NoAnnotationsServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getNoAnnotationsServiceHeaders()

	methodHeaders := getSimpleActionHeaders()
	simpleActionHandler := BindingMiddleware[SimpleRequest](
		genericHandler(server.SimpleAction, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		simpleActionPathParams, simpleActionQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /generated/simple_action", simpleActionHandler)

	methodHeaders = getAnotherActionHeaders()
	anotherActionHandler := BindingMiddleware[AnotherRequest](
		genericHandler(server.AnotherAction, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		anotherActionPathParams, anotherActionQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /generated/another_action", anotherActionHandler)

	return nil
}

// getNoAnnotationsServiceHeaders returns the service-level required headers for NoAnnotationsService
func getNoAnnotationsServiceHeaders() []*onekithttp.Header {
	return nil
}

// getSimpleActionHeaders returns the method-level required headers for SimpleAction
func getSimpleActionHeaders() []*onekithttp.Header {
	return nil
}

// getAnotherActionHeaders returns the method-level required headers for AnotherAction
func getAnotherActionHeaders() []*onekithttp.Header {
	return nil
}

// simpleActionPathParams contains path parameter configuration for SimpleAction
var simpleActionPathParams = []PathParamConfig{}

// simpleActionQueryParams contains query parameter configuration for SimpleAction
var simpleActionQueryParams = []QueryParamConfig{}

// anotherActionPathParams contains path parameter configuration for AnotherAction
var anotherActionPathParams = []PathParamConfig{}

// anotherActionQueryParams contains query parameter configuration for AnotherAction
var anotherActionQueryParams = []QueryParamConfig{}

// BasePathOnlyServiceServer is the server API for BasePathOnlyService service.
type BasePathOnlyServiceServer interface {
	ActionOne(context.Context, *ActionRequest) (*ActionResponse, error)
	ActionTwo(context.Context, *ActionRequest) (*ActionResponse, error)
}

// RegisterBasePathOnlyServiceServer registers the HTTP handlers for service BasePathOnlyService to the given mux.
func RegisterBasePathOnlyServiceServer(server BasePathOnlyServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getBasePathOnlyServiceHeaders()

	methodHeaders := getActionOneHeaders()
	actionOneHandler := BindingMiddleware[ActionRequest](
		genericHandler(server.ActionOne, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		actionOnePathParams, actionOneQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v2/action_one", actionOneHandler)

	methodHeaders = getActionTwoHeaders()
	actionTwoHandler := BindingMiddleware[ActionRequest](
		genericHandler(server.ActionTwo, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		actionTwoPathParams, actionTwoQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v2/action_two", actionTwoHandler)

	return nil
}

// getBasePathOnlyServiceHeaders returns the service-level required headers for BasePathOnlyService
func getBasePathOnlyServiceHeaders() []*onekithttp.Header {
	return nil
}

// getActionOneHeaders returns the method-level required headers for ActionOne
func getActionOneHeaders() []*onekithttp.Header {
	return nil
}

// getActionTwoHeaders returns the method-level required headers for ActionTwo
func getActionTwoHeaders() []*onekithttp.Header {
	return nil
}

// actionOnePathParams contains path parameter configuration for ActionOne
var actionOnePathParams = []PathParamConfig{}

// actionOneQueryParams contains query parameter configuration for ActionOne
var actionOneQueryParams = []QueryParamConfig{}

// actionTwoPathParams contains path parameter configuration for ActionTwo
var actionTwoPathParams = []PathParamConfig{}

// actionTwoQueryParams contains query parameter configuration for ActionTwo
var actionTwoQueryParams = []QueryParamConfig{}
