// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: body_selection.proto

package generated

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// BodySelectServiceServer is the server API for BodySelectService service.
type BodySelectServiceServer interface {
	UpdateProfile(context.Context, *UpdateProfileRequest) (*Profile, error)
	CreateNote(context.Context, *CreateNoteRequest) (*Note, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*Profile, error)
}

// RegisterBodySelectServiceServer registers the HTTP handlers for service BodySelectService to the given mux.
func RegisterBodySelectServiceServer(server BodySelectServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getBodySelectServiceHeaders()

	methodHeaders := getUpdateProfileHeaders()
	updateProfileHandler := BindingMiddleware[UpdateProfileRequest](
		genericHandler(server.UpdateProfile, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		updateProfilePathParams, updateProfileQueryParams,
		"PUT", "profile", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("PUT /api/v1/users/{user_id}/profile", updateProfileHandler)

	methodHeaders = getCreateNoteHeaders()
	createNoteHandler := BindingMiddleware[CreateNoteRequest](
		genericHandler(server.CreateNote, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		createNotePathParams, createNoteQueryParams,
		"POST", "note", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/notes", createNoteHandler)

	methodHeaders = getCreateProfileHeaders()
	createProfileHandler := BindingMiddleware[CreateProfileRequest](
		genericHandler(server.CreateProfile, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		createProfilePathParams, createProfileQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/profiles", createProfileHandler)

	return nil
}

// getBodySelectServiceHeaders returns the service-level required headers for BodySelectService
func getBodySelectServiceHeaders() []*onekithttp.Header {
	return nil
}

// getUpdateProfileHeaders returns the method-level required headers for UpdateProfile
func getUpdateProfileHeaders() []*onekithttp.Header {
	return nil
}

// getCreateNoteHeaders returns the method-level required headers for CreateNote
func getCreateNoteHeaders() []*onekithttp.Header {
	return nil
}

// getCreateProfileHeaders returns the method-level required headers for CreateProfile
func getCreateProfileHeaders() []*onekithttp.Header {
	return nil
}

// updateProfilePathParams contains path parameter configuration for UpdateProfile
var updateProfilePathParams = []PathParamConfig{
	{URLParam: "user_id", FieldName: "user_id"},
}

// updateProfileQueryParams contains query parameter configuration for UpdateProfile
var updateProfileQueryParams = []QueryParamConfig{
	{QueryName: "notify", FieldName: "notify", Required: false},
}

// createNotePathParams contains path parameter configuration for CreateNote
var createNotePathParams = []PathParamConfig{}

// createNoteQueryParams contains query parameter configuration for CreateNote
var createNoteQueryParams = []QueryParamConfig{
	{QueryName: "collection", FieldName: "collection", Required: false},
}

// createProfilePathParams contains path parameter configuration for CreateProfile
var createProfilePathParams = []PathParamConfig{}

// createProfileQueryParams contains query parameter configuration for CreateProfile
var createProfileQueryParams = []QueryParamConfig{}
