// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: cross_int64_service.proto

package crossint64

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// BarsServiceServer is the server API for BarsService service.
type BarsServiceServer interface {
	GetBars(context.Context, *GetBarsRequest) (*GetBarsResponse, error)
}

// RegisterBarsServiceServer registers the HTTP handlers for service BarsService to the given mux.
func RegisterBarsServiceServer(server BarsServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getBarsServiceHeaders()

	methodHeaders := getGetBarsHeaders()
	getBarsHandler := BindingMiddleware[GetBarsRequest](
		genericHandler(server.GetBars, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getBarsPathParams, getBarsQueryParams,
		"GET", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v2/bars", getBarsHandler)

	return nil
}

// getBarsServiceHeaders returns the service-level required headers for BarsService
func getBarsServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetBarsHeaders returns the method-level required headers for GetBars
func getGetBarsHeaders() []*onekithttp.Header {
	return nil
}

// getBarsPathParams contains path parameter configuration for GetBars
var getBarsPathParams = []PathParamConfig{}

// getBarsQueryParams contains query parameter configuration for GetBars
var getBarsQueryParams = []QueryParamConfig{
	{QueryName: "symbols", FieldName: "symbols", Required: false},
}
