// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: empty_request_body.proto

package emptyrequestbody

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// EmptyRequestBodyServiceServer is the server API for EmptyRequestBodyService service.
type EmptyRequestBodyServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	NoArgs(context.Context, *NoArgsRequest) (*NoArgsResponse, error)
}

// RegisterEmptyRequestBodyServiceServer registers the HTTP handlers for service EmptyRequestBodyService to the given mux.
func RegisterEmptyRequestBodyServiceServer(server EmptyRequestBodyServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getEmptyRequestBodyServiceHeaders()

	methodHeaders := getPingHeaders()
	pingHandler := BindingMiddleware[PingRequest](
		genericHandler(server.Ping, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		pingPathParams, pingQueryParams,
		"POST", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	pingHandler = config.wrapHandler(pingHandler, RequestMetadata{
		Service:     "testdata.empty_request_body.EmptyRequestBodyService",
		Method:      "Ping",
		Procedure:   "testdata.empty_request_body.EmptyRequestBodyService.Ping",
		HTTPMethod:  "POST",
		PathPattern: "/api/v1/ping",
	})
	config.mux.Handle("POST /api/v1/ping", pingHandler)

	methodHeaders = getNoArgsHeaders()
	noArgsHandler := BindingMiddleware[NoArgsRequest](
		genericHandler(server.NoArgs, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		noArgsPathParams, noArgsQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	noArgsHandler = config.wrapHandler(noArgsHandler, RequestMetadata{
		Service:     "testdata.empty_request_body.EmptyRequestBodyService",
		Method:      "NoArgs",
		Procedure:   "testdata.empty_request_body.EmptyRequestBodyService.NoArgs",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/no-args",
	})
	config.mux.Handle("GET /api/v1/no-args", noArgsHandler)

	return nil
}

// getEmptyRequestBodyServiceHeaders returns the service-level required headers for EmptyRequestBodyService
func getEmptyRequestBodyServiceHeaders() []*onekithttp.Header {
	return nil
}

// getPingHeaders returns the method-level required headers for Ping
func getPingHeaders() []*onekithttp.Header {
	return nil
}

// getNoArgsHeaders returns the method-level required headers for NoArgs
func getNoArgsHeaders() []*onekithttp.Header {
	return nil
}

// pingPathParams contains path parameter configuration for Ping
var pingPathParams = []PathParamConfig{}

// pingQueryParams contains query parameter configuration for Ping
var pingQueryParams = []QueryParamConfig{}

// noArgsPathParams contains path parameter configuration for NoArgs
var noArgsPathParams = []PathParamConfig{}

// noArgsQueryParams contains query parameter configuration for NoArgs
var noArgsQueryParams = []QueryParamConfig{}
