// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: enum_encoding.proto

package enumencoding

import (
	"context"

	onekithttp "github.com/corezio/onekit/http"
)

// EnumEncodingServiceServer is the server API for EnumEncodingService service.
type EnumEncodingServiceServer interface {
	GetEnumTest(context.Context, *GetEnumTestRequest) (*EnumEncodingTest, error)
}

// RegisterEnumEncodingServiceServer registers the HTTP handlers for service EnumEncodingService to the given mux.
func RegisterEnumEncodingServiceServer(server EnumEncodingServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getEnumEncodingServiceHeaders()

	methodHeaders := getGetEnumTestHeaders()
	getEnumTestHandler := BindingMiddleware[GetEnumTestRequest](
		genericHandler(server.GetEnumTest, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getEnumTestPathParams, getEnumTestQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	getEnumTestHandler = config.wrapHandler(getEnumTestHandler, RequestMetadata{
		Service:     "testdata.enumencoding.EnumEncodingService",
		Method:      "GetEnumTest",
		Procedure:   "testdata.enumencoding.EnumEncodingService.GetEnumTest",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/test/enum/{id}",
	})
	config.mux.Handle("GET /api/v1/test/enum/{id}", getEnumTestHandler)

	return nil
}

// getEnumEncodingServiceHeaders returns the service-level required headers for EnumEncodingService
func getEnumEncodingServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetEnumTestHeaders returns the method-level required headers for GetEnumTest
func getGetEnumTestHeaders() []*onekithttp.Header {
	return nil
}

// getEnumTestPathParams contains path parameter configuration for GetEnumTest
var getEnumTestPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// getEnumTestQueryParams contains query parameter configuration for GetEnumTest
var getEnumTestQueryParams = []QueryParamConfig{}
