// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: enum_encoding.proto

package enumencoding

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// ErrorHandler is called when an error occurs.
//
// You can:
//   - Set headers via w.Header().Set(...)
//   - Set status code via w.WriteHeader(...)
//   - Return a proto.Message to be marshaled as the response body
//   - Return nil to use the default error response (ValidationError or Error)
//
// If you write directly to w (via w.Write()), the response is considered
// complete and no further writing occurs.
//
// Use errors.As() to inspect error types: *onekithttp.ValidationError or *onekithttp.Error
type ErrorHandler func(w http.ResponseWriter, r *http.Request, err error) proto.Message

// RequestMetadata identifies the generated route handling a request.
type RequestMetadata struct {
	Service     string
	Method      string
	Procedure   string
	HTTPMethod  string
	PathPattern string
}

// RequestResult describes the response produced by a generated handler.
type RequestResult struct {
	StatusCode   int
	BytesWritten int64
	Duration     time.Duration
}

// RequestObserver receives dependency-free request lifecycle callbacks.
// RequestStarted may enrich the context passed to the handler and middleware.
type RequestObserver interface {
	RequestStarted(context.Context, RequestMetadata) context.Context
	RequestFinished(context.Context, RequestMetadata, RequestResult)
}

type requestMetadataContextKey struct{}

// RequestMetadataFromContext returns metadata for the matched generated route.
func RequestMetadataFromContext(ctx context.Context) (RequestMetadata, bool) {
	metadata, ok := ctx.Value(requestMetadataContextKey{}).(RequestMetadata)
	return metadata, ok
}

// Middleware wraps a generated HTTP handler. Middleware passed to WithMiddleware
// is applied in declaration order, so the first middleware is the outermost.
type Middleware func(http.Handler) http.Handler

// RequestIDGenerator creates a request ID when the configured request header is absent.
type RequestIDGenerator func() string

type requestIDContextKey struct{}

// RequestIDFromContext returns the request ID installed by WithRequestID.
func RequestIDFromContext(ctx context.Context) (string, bool) {
	requestID, ok := ctx.Value(requestIDContextKey{}).(string)
	return requestID, ok && requestID != ""
}

func defaultRequestIDGenerator() string {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(value[:])
}

// ServerOption configures a Server
type ServerOption func(c *serverConfiguration)

const DefaultMaxRequestBytes int64 = 10 << 20

type serverConfiguration struct {
	mux                *http.ServeMux
	withMux            bool
	errorHandler       ErrorHandler
	marshalOpts        protojson.MarshalOptions
	maxRequestBytes    int64
	middlewares        []Middleware
	requestIDHeader    string
	requestIDGenerator RequestIDGenerator
	observer           RequestObserver
}

func (c *serverConfiguration) wrapHandler(handler http.Handler, metadata RequestMetadata) http.Handler {
	for i := len(c.middlewares) - 1; i >= 0; i-- {
		if c.middlewares[i] != nil {
			handler = c.middlewares[i](handler)
		}
	}
	if c.observer != nil {
		handler = observationMiddleware(c.observer, metadata)(handler)
	}
	if c.requestIDHeader != "" {
		handler = requestIDMiddleware(c.requestIDHeader, c.requestIDGenerator)(handler)
	}
	handler = routeMetadataMiddleware(metadata)(handler)
	return handler
}

func requestIDMiddleware(headerName string, generate RequestIDGenerator) Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			requestID := r.Header.Get(headerName)
			if requestID == "" && generate != nil {
				requestID = generate()
			}
			if requestID != "" {
				w.Header().Set(headerName, requestID)
				r = r.WithContext(context.WithValue(r.Context(), requestIDContextKey{}, requestID))
			}
			next.ServeHTTP(w, r)
		})
	}
}

func routeMetadataMiddleware(metadata RequestMetadata) Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := context.WithValue(r.Context(), requestMetadataContextKey{}, metadata)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

type observationResponseWriter struct {
	http.ResponseWriter
	statusCode   int
	bytesWritten int64
}

func (w *observationResponseWriter) WriteHeader(statusCode int) {
	if w.statusCode != 0 {
		return
	}
	w.statusCode = statusCode
	w.ResponseWriter.WriteHeader(statusCode)
}

func (w *observationResponseWriter) Write(body []byte) (int, error) {
	if w.statusCode == 0 {
		w.statusCode = http.StatusOK
	}
	n, err := w.ResponseWriter.Write(body)
	w.bytesWritten += int64(n)
	return n, err
}

func (w *observationResponseWriter) Flush() {
	if w.statusCode == 0 {
		w.WriteHeader(http.StatusOK)
	}
	if flusher, ok := w.ResponseWriter.(http.Flusher); ok {
		flusher.Flush()
	}
}

func (w *observationResponseWriter) Unwrap() http.ResponseWriter {
	return w.ResponseWriter
}

func observationMiddleware(observer RequestObserver, metadata RequestMetadata) Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := observer.RequestStarted(r.Context(), metadata)
			if ctx == nil {
				ctx = r.Context()
			}
			started := time.Now()
			capture := &observationResponseWriter{ResponseWriter: w}
			defer func() {
				statusCode := capture.statusCode
				if statusCode == 0 {
					statusCode = http.StatusOK
				}
				observer.RequestFinished(ctx, metadata, RequestResult{
					StatusCode:   statusCode,
					BytesWritten: capture.bytesWritten,
					Duration:     time.Since(started),
				})
			}()
			next.ServeHTTP(capture, r.WithContext(ctx))
		})
	}
}

func getDefaultConfiguration() *serverConfiguration {
	return &serverConfiguration{
		mux:             http.DefaultServeMux,
		withMux:         false,
		maxRequestBytes: DefaultMaxRequestBytes,
	}
}

func getConfiguration(options ...ServerOption) *serverConfiguration {
	configuration := getDefaultConfiguration()
	for _, option := range options {
		option(configuration)
	}
	return configuration
}

// WithMux configures the Server to use the given ServeMux
func WithMux(mux *http.ServeMux) ServerOption {
	return func(c *serverConfiguration) {
		c.mux = mux
		c.withMux = true
	}
}

// WithErrorHandler configures a custom error handler for the server.
func WithErrorHandler(handler ErrorHandler) ServerOption {
	return func(c *serverConfiguration) {
		c.errorHandler = handler
	}
}

// WithMarshalOptions configures the protojson.MarshalOptions used when serializing
// JSON responses (including SSE events and error bodies). The zero value preserves
// default behavior. Use this to surface zero-value fields with EmitUnpopulated,
// switch to proto field names with UseProtoNames, or tune any other protojson knob.
func WithMarshalOptions(opts protojson.MarshalOptions) ServerOption {
	return func(c *serverConfiguration) {
		c.marshalOpts = opts
	}
}

// WithMaxRequestBytes configures the maximum request body size accepted by
// generated binding handlers. Values <= 0 disable request body size limiting.
func WithMaxRequestBytes(maxBytes int64) ServerOption {
	return func(c *serverConfiguration) {
		c.maxRequestBytes = maxBytes
	}
}

// WithMiddleware applies middleware to every handler registered by the service.
// The first middleware is the outermost. Nil middleware values are ignored.
func WithMiddleware(middleware ...Middleware) ServerOption {
	return func(c *serverConfiguration) {
		c.middlewares = append(c.middlewares, middleware...)
	}
}

// WithRequestObserver adds request lifecycle callbacks for tracing, logging, or metrics.
func WithRequestObserver(observer RequestObserver) ServerOption {
	return func(c *serverConfiguration) {
		c.observer = observer
	}
}

// WithRequestID enables request-ID propagation for every generated handler.
// Existing inbound IDs are preserved; otherwise a random 128-bit ID is generated.
// The ID is returned in the same response header and is available through RequestIDFromContext.
// An empty headerName uses "X-Request-ID".
func WithRequestID(headerName string) ServerOption {
	return WithRequestIDGenerator(headerName, defaultRequestIDGenerator)
}

// WithRequestIDGenerator enables request IDs using a custom generator.
// It is useful when IDs must come from an existing tracing or identity system.
func WithRequestIDGenerator(headerName string, generate RequestIDGenerator) ServerOption {
	return func(c *serverConfiguration) {
		if headerName == "" {
			headerName = "X-Request-ID"
		}
		c.requestIDHeader = headerName
		c.requestIDGenerator = generate
	}
}
