// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: flatten.proto

package flatten

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// FlattenServiceServer is the server API for FlattenService service.
type FlattenServiceServer interface {
	TestSimpleFlatten(context.Context, *SimpleFlatten) (*SimpleFlatten, error)
	TestDualFlatten(context.Context, *DualFlatten) (*DualFlatten, error)
	TestMixedFlatten(context.Context, *MixedFlatten) (*MixedFlatten, error)
	TestPlainNested(context.Context, *PlainNested) (*PlainNested, error)
}

// RegisterFlattenServiceServer registers the HTTP handlers for service FlattenService to the given mux.
func RegisterFlattenServiceServer(server FlattenServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getFlattenServiceHeaders()

	methodHeaders := getTestSimpleFlattenHeaders()
	testSimpleFlattenHandler := BindingMiddleware[SimpleFlatten](
		genericHandler(server.TestSimpleFlatten, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testSimpleFlattenPathParams, testSimpleFlattenQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/flatten/simple", testSimpleFlattenHandler)

	methodHeaders = getTestDualFlattenHeaders()
	testDualFlattenHandler := BindingMiddleware[DualFlatten](
		genericHandler(server.TestDualFlatten, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testDualFlattenPathParams, testDualFlattenQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/flatten/dual", testDualFlattenHandler)

	methodHeaders = getTestMixedFlattenHeaders()
	testMixedFlattenHandler := BindingMiddleware[MixedFlatten](
		genericHandler(server.TestMixedFlatten, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testMixedFlattenPathParams, testMixedFlattenQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/flatten/mixed", testMixedFlattenHandler)

	methodHeaders = getTestPlainNestedHeaders()
	testPlainNestedHandler := BindingMiddleware[PlainNested](
		genericHandler(server.TestPlainNested, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testPlainNestedPathParams, testPlainNestedQueryParams,
		"POST", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/flatten/plain", testPlainNestedHandler)

	return nil
}

// getFlattenServiceHeaders returns the service-level required headers for FlattenService
func getFlattenServiceHeaders() []*onekithttp.Header {
	return nil
}

// getTestSimpleFlattenHeaders returns the method-level required headers for TestSimpleFlatten
func getTestSimpleFlattenHeaders() []*onekithttp.Header {
	return nil
}

// getTestDualFlattenHeaders returns the method-level required headers for TestDualFlatten
func getTestDualFlattenHeaders() []*onekithttp.Header {
	return nil
}

// getTestMixedFlattenHeaders returns the method-level required headers for TestMixedFlatten
func getTestMixedFlattenHeaders() []*onekithttp.Header {
	return nil
}

// getTestPlainNestedHeaders returns the method-level required headers for TestPlainNested
func getTestPlainNestedHeaders() []*onekithttp.Header {
	return nil
}

// testSimpleFlattenPathParams contains path parameter configuration for TestSimpleFlatten
var testSimpleFlattenPathParams = []PathParamConfig{}

// testSimpleFlattenQueryParams contains query parameter configuration for TestSimpleFlatten
var testSimpleFlattenQueryParams = []QueryParamConfig{}

// testDualFlattenPathParams contains path parameter configuration for TestDualFlatten
var testDualFlattenPathParams = []PathParamConfig{}

// testDualFlattenQueryParams contains query parameter configuration for TestDualFlatten
var testDualFlattenQueryParams = []QueryParamConfig{}

// testMixedFlattenPathParams contains path parameter configuration for TestMixedFlatten
var testMixedFlattenPathParams = []PathParamConfig{}

// testMixedFlattenQueryParams contains query parameter configuration for TestMixedFlatten
var testMixedFlattenQueryParams = []QueryParamConfig{}

// testPlainNestedPathParams contains path parameter configuration for TestPlainNested
var testPlainNestedPathParams = []PathParamConfig{}

// testPlainNestedQueryParams contains query parameter configuration for TestPlainNested
var testPlainNestedQueryParams = []QueryParamConfig{}
