// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: int64_repeated_nested_encoding.proto

package int64repeatednested

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// StockServiceServer is the server API for StockService service.
type StockServiceServer interface {
	GetStocks(context.Context, *GetStocksRequest) (*GetStocksResponse, error)
}

// RegisterStockServiceServer registers the HTTP handlers for service StockService to the given mux.
func RegisterStockServiceServer(server StockServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getStockServiceHeaders()

	methodHeaders := getGetStocksHeaders()
	getStocksHandler := BindingMiddleware[GetStocksRequest](
		genericHandler(server.GetStocks, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getStocksPathParams, getStocksQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	getStocksHandler = config.wrapHandler(getStocksHandler, RequestMetadata{
		Service:     "testdata.int64repeatednested.StockService",
		Method:      "GetStocks",
		Procedure:   "testdata.int64repeatednested.StockService.GetStocks",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/stocks/{market}",
	})
	config.mux.Handle("GET /api/v1/stocks/{market}", getStocksHandler)

	return nil
}

// getStockServiceHeaders returns the service-level required headers for StockService
func getStockServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetStocksHeaders returns the method-level required headers for GetStocks
func getGetStocksHeaders() []*onekithttp.Header {
	return nil
}

// getStocksPathParams contains path parameter configuration for GetStocks
var getStocksPathParams = []PathParamConfig{
	{URLParam: "market", FieldName: "market"},
}

// getStocksQueryParams contains query parameter configuration for GetStocks
var getStocksQueryParams = []QueryParamConfig{}
