// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: int64_encoding.proto

package int64encoding

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// Int64EncodingServiceServer is the server API for Int64EncodingService service.
type Int64EncodingServiceServer interface {
	GetInt64Test(context.Context, *GetInt64TestRequest) (*Int64EncodingTest, error)
}

// RegisterInt64EncodingServiceServer registers the HTTP handlers for service Int64EncodingService to the given mux.
func RegisterInt64EncodingServiceServer(server Int64EncodingServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getInt64EncodingServiceHeaders()

	methodHeaders := getGetInt64TestHeaders()
	getInt64TestHandler := BindingMiddleware[GetInt64TestRequest](
		genericHandler(server.GetInt64Test, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getInt64TestPathParams, getInt64TestQueryParams,
		"GET", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /api/v1/test/int64/{id}", getInt64TestHandler)

	return nil
}

// getInt64EncodingServiceHeaders returns the service-level required headers for Int64EncodingService
func getInt64EncodingServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetInt64TestHeaders returns the method-level required headers for GetInt64Test
func getGetInt64TestHeaders() []*onekithttp.Header {
	return nil
}

// getInt64TestPathParams contains path parameter configuration for GetInt64Test
var getInt64TestPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// getInt64TestQueryParams contains query parameter configuration for GetInt64Test
var getInt64TestQueryParams = []QueryParamConfig{}
