// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: nullable.proto

package nullable

import (
	"context"

	onekithttp "github.com/corezio/onekit/http"
)

// NullableServiceServer is the server API for NullableService service.
type NullableServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
}

// RegisterNullableServiceServer registers the HTTP handlers for service NullableService to the given mux.
func RegisterNullableServiceServer(server NullableServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getNullableServiceHeaders()

	methodHeaders := getGetUserHeaders()
	getUserHandler := BindingMiddleware[GetUserRequest](
		genericHandler(server.GetUser, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getUserPathParams, getUserQueryParams,
		"GET", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	getUserHandler = config.wrapHandler(getUserHandler, RequestMetadata{
		Service:     "testdata.nullable.NullableService",
		Method:      "GetUser",
		Procedure:   "testdata.nullable.NullableService.GetUser",
		HTTPMethod:  "GET",
		PathPattern: "/api/v1/users/{id}",
	})
	config.mux.Handle("GET /api/v1/users/{id}", getUserHandler)

	methodHeaders = getUpdateUserHeaders()
	updateUserHandler := BindingMiddleware[UpdateUserRequest](
		genericHandler(server.UpdateUser, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		updateUserPathParams, updateUserQueryParams,
		"PUT", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	updateUserHandler = config.wrapHandler(updateUserHandler, RequestMetadata{
		Service:     "testdata.nullable.NullableService",
		Method:      "UpdateUser",
		Procedure:   "testdata.nullable.NullableService.UpdateUser",
		HTTPMethod:  "PUT",
		PathPattern: "/api/v1/users/{id}",
	})
	config.mux.Handle("PUT /api/v1/users/{id}", updateUserHandler)

	return nil
}

// getNullableServiceHeaders returns the service-level required headers for NullableService
func getNullableServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetUserHeaders returns the method-level required headers for GetUser
func getGetUserHeaders() []*onekithttp.Header {
	return nil
}

// getUpdateUserHeaders returns the method-level required headers for UpdateUser
func getUpdateUserHeaders() []*onekithttp.Header {
	return nil
}

// getUserPathParams contains path parameter configuration for GetUser
var getUserPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// getUserQueryParams contains query parameter configuration for GetUser
var getUserQueryParams = []QueryParamConfig{}

// updateUserPathParams contains path parameter configuration for UpdateUser
var updateUserPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// updateUserQueryParams contains query parameter configuration for UpdateUser
var updateUserQueryParams = []QueryParamConfig{}
