// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: oneof_discriminator.proto

package oneofdiscriminator

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// OneofDiscriminatorServiceServer is the server API for OneofDiscriminatorService service.
type OneofDiscriminatorServiceServer interface {
	TestFlattenedEvent(context.Context, *FlattenedEvent) (*FlattenedEvent, error)
	TestNestedEvent(context.Context, *NestedEvent) (*NestedEvent, error)
	TestPlainEvent(context.Context, *PlainEvent) (*PlainEvent, error)
}

// RegisterOneofDiscriminatorServiceServer registers the HTTP handlers for service OneofDiscriminatorService to the given mux.
func RegisterOneofDiscriminatorServiceServer(server OneofDiscriminatorServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getOneofDiscriminatorServiceHeaders()

	methodHeaders := getTestFlattenedEventHeaders()
	testFlattenedEventHandler := BindingMiddleware[FlattenedEvent](
		genericHandler(server.TestFlattenedEvent, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testFlattenedEventPathParams, testFlattenedEventQueryParams,
		"POST", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	testFlattenedEventHandler = config.wrapHandler(testFlattenedEventHandler, RequestMetadata{
		Service:     "testdata.oneof_discriminator.OneofDiscriminatorService",
		Method:      "TestFlattenedEvent",
		Procedure:   "testdata.oneof_discriminator.OneofDiscriminatorService.TestFlattenedEvent",
		HTTPMethod:  "POST",
		PathPattern: "/api/v1/events/flattened",
	})
	config.mux.Handle("POST /api/v1/events/flattened", testFlattenedEventHandler)

	methodHeaders = getTestNestedEventHeaders()
	testNestedEventHandler := BindingMiddleware[NestedEvent](
		genericHandler(server.TestNestedEvent, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testNestedEventPathParams, testNestedEventQueryParams,
		"POST", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	testNestedEventHandler = config.wrapHandler(testNestedEventHandler, RequestMetadata{
		Service:     "testdata.oneof_discriminator.OneofDiscriminatorService",
		Method:      "TestNestedEvent",
		Procedure:   "testdata.oneof_discriminator.OneofDiscriminatorService.TestNestedEvent",
		HTTPMethod:  "POST",
		PathPattern: "/api/v1/events/nested",
	})
	config.mux.Handle("POST /api/v1/events/nested", testNestedEventHandler)

	methodHeaders = getTestPlainEventHeaders()
	testPlainEventHandler := BindingMiddleware[PlainEvent](
		genericHandler(server.TestPlainEvent, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		testPlainEventPathParams, testPlainEventQueryParams,
		"POST", "", config.maxRequestBytes, config.errorHandler, config.marshalOpts,
	)

	testPlainEventHandler = config.wrapHandler(testPlainEventHandler, RequestMetadata{
		Service:     "testdata.oneof_discriminator.OneofDiscriminatorService",
		Method:      "TestPlainEvent",
		Procedure:   "testdata.oneof_discriminator.OneofDiscriminatorService.TestPlainEvent",
		HTTPMethod:  "POST",
		PathPattern: "/api/v1/events/plain",
	})
	config.mux.Handle("POST /api/v1/events/plain", testPlainEventHandler)

	return nil
}

// getOneofDiscriminatorServiceHeaders returns the service-level required headers for OneofDiscriminatorService
func getOneofDiscriminatorServiceHeaders() []*onekithttp.Header {
	return nil
}

// getTestFlattenedEventHeaders returns the method-level required headers for TestFlattenedEvent
func getTestFlattenedEventHeaders() []*onekithttp.Header {
	return nil
}

// getTestNestedEventHeaders returns the method-level required headers for TestNestedEvent
func getTestNestedEventHeaders() []*onekithttp.Header {
	return nil
}

// getTestPlainEventHeaders returns the method-level required headers for TestPlainEvent
func getTestPlainEventHeaders() []*onekithttp.Header {
	return nil
}

// testFlattenedEventPathParams contains path parameter configuration for TestFlattenedEvent
var testFlattenedEventPathParams = []PathParamConfig{}

// testFlattenedEventQueryParams contains query parameter configuration for TestFlattenedEvent
var testFlattenedEventQueryParams = []QueryParamConfig{}

// testNestedEventPathParams contains path parameter configuration for TestNestedEvent
var testNestedEventPathParams = []PathParamConfig{}

// testNestedEventQueryParams contains query parameter configuration for TestNestedEvent
var testNestedEventQueryParams = []QueryParamConfig{}

// testPlainEventPathParams contains path parameter configuration for TestPlainEvent
var testPlainEventPathParams = []PathParamConfig{}

// testPlainEventQueryParams contains query parameter configuration for TestPlainEvent
var testPlainEventQueryParams = []QueryParamConfig{}
