// Code generated by protoc-gen-onekit-go-http. DO NOT EDIT.
// source: sse.proto

package generated

import (
	"context"

	onekithttp "github.com/1homsi/onekit/http"
)

// SSEServiceServer is the server API for SSEService service.
type SSEServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*StatusResponse, error)
	StreamEvents(context.Context, *StreamEventsRequest, SSESender) error
	StreamResourceEvents(context.Context, *StreamResourceEventsRequest, SSESender) error
	StreamFilteredEvents(context.Context, *StreamFilteredEventsRequest, SSESender) error
}

// RegisterSSEServiceServer registers the HTTP handlers for service SSEService to the given mux.
func RegisterSSEServiceServer(server SSEServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getSSEServiceHeaders()

	methodHeaders := getGetStatusHeaders()
	getStatusHandler := BindingMiddleware[GetStatusRequest](
		genericHandler(server.GetStatus, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getStatusPathParams, getStatusQueryParams,
		"GET", "", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /api/v1/status", getStatusHandler)

	methodHeaders = getStreamEventsHeaders()
	streamEventsHandler := SSEHandler[StreamEventsRequest](
		server.StreamEvents, config.errorHandler, serviceHeaders, methodHeaders,
		streamEventsPathParams, streamEventsQueryParams,
		"GET", config.marshalOpts,
	)

	config.mux.Handle("GET /api/v1/events", streamEventsHandler)

	methodHeaders = getStreamResourceEventsHeaders()
	streamResourceEventsHandler := SSEHandler[StreamResourceEventsRequest](
		server.StreamResourceEvents, config.errorHandler, serviceHeaders, methodHeaders,
		streamResourceEventsPathParams, streamResourceEventsQueryParams,
		"GET", config.marshalOpts,
	)

	config.mux.Handle("GET /api/v1/resources/{resource_id}/events", streamResourceEventsHandler)

	methodHeaders = getStreamFilteredEventsHeaders()
	streamFilteredEventsHandler := SSEHandler[StreamFilteredEventsRequest](
		server.StreamFilteredEvents, config.errorHandler, serviceHeaders, methodHeaders,
		streamFilteredEventsPathParams, streamFilteredEventsQueryParams,
		"GET", config.marshalOpts,
	)

	config.mux.Handle("GET /api/v1/events/filtered", streamFilteredEventsHandler)

	return nil
}

// getSSEServiceHeaders returns the service-level required headers for SSEService
func getSSEServiceHeaders() []*onekithttp.Header {
	return nil
}

// getGetStatusHeaders returns the method-level required headers for GetStatus
func getGetStatusHeaders() []*onekithttp.Header {
	return nil
}

// getStreamEventsHeaders returns the method-level required headers for StreamEvents
func getStreamEventsHeaders() []*onekithttp.Header {
	return nil
}

// getStreamResourceEventsHeaders returns the method-level required headers for StreamResourceEvents
func getStreamResourceEventsHeaders() []*onekithttp.Header {
	return nil
}

// getStreamFilteredEventsHeaders returns the method-level required headers for StreamFilteredEvents
func getStreamFilteredEventsHeaders() []*onekithttp.Header {
	return nil
}

// getStatusPathParams contains path parameter configuration for GetStatus
var getStatusPathParams = []PathParamConfig{}

// getStatusQueryParams contains query parameter configuration for GetStatus
var getStatusQueryParams = []QueryParamConfig{}

// streamEventsPathParams contains path parameter configuration for StreamEvents
var streamEventsPathParams = []PathParamConfig{}

// streamEventsQueryParams contains query parameter configuration for StreamEvents
var streamEventsQueryParams = []QueryParamConfig{}

// streamResourceEventsPathParams contains path parameter configuration for StreamResourceEvents
var streamResourceEventsPathParams = []PathParamConfig{
	{URLParam: "resource_id", FieldName: "resource_id"},
}

// streamResourceEventsQueryParams contains query parameter configuration for StreamResourceEvents
var streamResourceEventsQueryParams = []QueryParamConfig{}

// streamFilteredEventsPathParams contains path parameter configuration for StreamFilteredEvents
var streamFilteredEventsPathParams = []PathParamConfig{}

// streamFilteredEventsQueryParams contains query parameter configuration for StreamFilteredEvents
var streamFilteredEventsQueryParams = []QueryParamConfig{
	{QueryName: "type", FieldName: "event_type", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
}
